---
title: Mutlinomial logistic regression model trial
---

#WARNING

This is a Bayesian method. Without a good understanding of how it works or how one should interpret its results, this is not recommended.

```{r set_env}
#'load knitr
library(knitr);library(plyr);library(dplyr);library(data.table);library(purrr);library(ggplot2)

#'load model libs
library(gam);library(mgcv);library(gamm4);library(itsadug)

#'suppress all code output but run code
opts_chunk$set(eval = FALSE)
```



```{r load_data}
#'load data.goose.clean
source("dataprep.R")

fams.expand = fams.expand %>% filter(flocksize > 0)

fams.expand$pred = as.factor(fams.expand$pred)
fams$pred = as.factor(fams$pred)
```


```{r load_libs}
#'load libs for multinomial logit regression
library(MCMCglmm)
library(nnet)
```

```{r}
#'try the multlogit model, first set famsize as a factor
fams.expand$famsize = as.factor(fams.expand$famsize)

a = fams.expand[sample(dim(fams.expand)[1], 200),]
#'check levels
levels(fams.expand$famsize)

#'run an mcmcglmm
m1 = MCMCglmm(famsize ~ trait - 1 + lon, 
              rcov = ~ idh(trait):units,
              family = "categorical", data = a)

summary(m1)
plot(m1)
```

