---
title: Constructing a lemming index
---

```{r set_env}
#'load knitr
library(knitr);library(plyr);library(dplyr);library(data.table);library(purrr);library(ggplot2);library(readxl);library(readODS)

#'suppress all code output but run code
opts_chunk$set(eval = FALSE)
opts_knit$set(root.dir = "~/git/thesis/")
```

```{r load_data}
#'read in the file
lindex = read_ods("~/git/thesis/arcticbirds_lemming_abundance.ods", sheet = 1)

#'set NA to 0 
# DO NOT SET NA TO 0. NA MEANS NA.
# lindex$index[is.na(lindex$index)] = 0

#'read in Nolet's lemming and predation index
nolet.pi = read_excel("~/git/thesis/Brent_pop_model_data_predation_index.xlsx", sheet = 4)
```

The predation index is $p = 0.5*(A_{t-1}– A_t + 3)$.

```{r get_index}
#'get lemming values by year
lemming.w = lindex %>% group_by(year = as.numeric(year)) %>% summarise(l.index = mean(index, na.rm = T))

#'get the predation index

lemming.w$p.index = NA

for(i in 1:dim(lemming.w)[1]){
  lemming.w[i,"p.index"] = ifelse(i ==1, NA, (lemming.w[i-1,"l.index"] - lemming.w[i,"l.index"] + 2)/2)
}

#assign identifier
lemming.w$zone = "Kanin:Yenisey"

#'get nolet index
lemming.e = nolet.pi %>% group_by(year = as.numeric(Year)) %>% summarise(l.index = LC, p.index = PI)

#'assign zone
lemming.e$zone = "Taimyr"

#'rbind
lemmings = rbind(lemming.e, lemming.w)

#'melt
lemmings = melt(as.data.frame(lemmings), id.vars = c("zone", "year"))
```

```{r write_csv}
#lemming.w = lemming.w %>% group_by(year) %>% mutate(pred = cut(p.index, c(0:3), c(1:3)))

write.csv(lemming.w, "lemmings.csv")
write.csv(lemming.e, "lemming_nolet.csv")
```

## Lemming index, 1999 and before

