---
title: Flock level models
---

# Source data

```{r load_dataprep}
library(maps); library(sjPlot)
source("dataprep.R")
library(mgcv); library(lme4)
```

# Flocksize ~ longitude

Model with flocksize as response, lon-lat, days, p.index, as predictors, others as random effects.

```{r run_glmer}
#geese = geese %>% filter(complete.cases(lon, t_since_in, p.index, Breeding_year, Observer, Food_type))

flockmod = glmer(flocksize ~ distkol + t_since_in + p.index + (1|Breeding_year) + (1|Observer) + (1|Food_type), data = geese, family = poisson)

flockmod_fam = bam(flocksize ~ ti(meanfam) + distkol + t_since_in + p.index + ti(fams) + ti(meanfam, fams) + s(Breeding_year, bs = "re") + s(Observer, bs = "re") + s(Food_type, bs = "re"), family = "poisson", data = fams)

```

```{r summary}
summary(flockmod_fam)
```

# Number of families ~ flocksize

```{r gam_fams}
fams2 = fams %>% filter(flocksize>0, flocksize == N_sampled) %>% plyr::mutate(propjuv = propjuv/100)

famsmod = gamm4(fams ~ s(flocksize) + distkol + p.index, random = ~ (p.index|Breeding_year) + (1|Observer) + (1|Food_type), data = fams2, family = poisson)
```

```{r}
summary(famsmod)
```

```{r}
w = geese %>% group_by(Breeding_year) %>% summarise(prevwinter = first(durwinter))

y = 2001:2017

geese = merge(geese, cbind(w[,"prevwinter"],y), by.x = "Breeding_year", by.y = "y", all.x = T)

```


# Juveniles in flocks

```{r arctic_oscillation}
#a = data.frame(a = letters[1:16], b = as.factor(2001:2016))
#fams$propjuv = fams$propjuv/100

#'get arctic oscillation data
source("arctic_oscillation.r")

#'merge data

geese = merge(geese, ao_summer, by.x = "Breeding_year", by.y = "year")
```

```{r run_modjuvs}
#'using arctic birds index
modjuvs = gam(propjuv ~ distkol + flocksize + p.index + s(t_since_in) + s(Breeding_year, bs = "re") + s(Observer, bs = "re") + s(Food_type, bs = "re"), family = binomial, data = geese)

#'using nolet data
modjuvs2 = gam(propjuv ~ distkol + flocksize + pinnolet + s(Breeding_year, bs = "re") + s(t_since_in) + s(Observer, bs = "re") + s(Food_type, bs = "re"), family = binomial, data = geese)

#'using aos
modjuvs3 = gam(propjuv ~ aos + s(Breeding_year, bs = "re") + s(t_since_in) + s(Observer, bs = "re") + s(Food_type, bs = "re"), family = binomial, data = geese)

#'using gamm

modjuvs0 = gamm(propjuv ~ pinnolet + s(t_since_in), random = list(Breeding_year = ~1, Food_type = ~1, Observer = ~1), family = binomial, data = geese)
```

```{r}
summary(modjuvs0$gam)
```


# Export models

```{r}
save(modjuvs, modjuvs2, flockmod, famsmod, mod03, mod03.gorg, mod03.gorg.s, fams.expand.sub, fams.expand, file = "goosemods_pres.RData")
```
