---
title: Goose flock data
subtitle: Population trends
bibliography: ~/git/thesis/geese_citations.bib
fontsize: 10pt
output: 
  beamer_presentation: 
    colortheme: seagull
    theme: Luebeck
link-citations: true
citecolor: Emerald
---

# Sampling frequency

```{r, include=FALSE}
#'load knitr
library(knitr)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code/")
```

```{r load_clean_data, include=FALSE}
#'load data
goose_clean = read.csv("data.clean.goose.csv")

#assign zones
goose_clean$zone = ifelse(goose_clean$Region %in% c("DU","KLE","RG","WES","WG"),
       "Rhinelands",
       ifelse(goose_clean$Region %in% c("LER","DR","GR"),
              "East Frisia",
       ifelse(goose_clean$Region %in% c("FR","FL","NH"),
              "IJsselmeer",
              ifelse(goose_clean$Region %in% c("ZL","ZH"),
                     "Southwest", "Other"))))
```

```{r create_limited_df, include=FALSE}
#'create limited data frame
goose_time = goose_clean[,c("Region","Breeding_year","Total_flock","Perc.JV","time")]

#'set time as posixct
goose_time$time = as.Date(goose_time$time)

#'where are the NAs?
summary(goose_time[is.na(goose_time$Region),])

#'complete cases for time
goose_time = goose_time[complete.cases(goose_time),]

#'where are the NAs?
apply(goose_time, 2, function(x){sum(is.na(x))})
```

```{r assign_new_zones_ts}
#'assign new zones
goose_time$zone = ifelse(goose_time$Region %in% c("DU","KLE","RG","WES","WG","LI"),
       "Rhinelands",
       ifelse(goose_time$Region %in% c("LER","DR","GR"),
              "East Frisia",
       ifelse(goose_time$Region %in% c("FR","FL","NH"),
              "IJsselmeer", 
              ifelse(goose_time$Region %in% c("ZL","ZH"),
                     "Southwest", "Other"))))
```


```{r tilemap_space_time, fig.cap= "Sampling times in each region. Sampling is not even over zones.", fig.width=7, fig.height=3, message=FALSE}
library(ggplot2)
library(reshape)

ggplot(data = melt(as.data.frame(table(goose_time[,c("Breeding_year","zone")]))),
       aes(x=zone, y=Breeding_year, fill = value))+
  geom_tile(col = 1)+
  scale_fill_gradient2(midpoint = 50, high = "seagreen4", 
                    guide = "legend",
                    low = "darkred", breaks= c(0,50,100),
                    labels = c("< 25","25 - 100", "> 100"))+
  theme_minimal()
```

# Global flock size trend

```{r create_aggregate, warning=FALSE, include=FALSE}
#'create a df aggregated as means with time as the factor
goose_aggregate = aggregate(goose_time,
                     list(goose_time$time, goose_time$Region),
                     mean)

#'subset to remove factor date and region
goose_aggregate = goose_aggregate[,c("Group.2","Breeding_year",
                                     "Total_flock","Perc.JV",
                                     "time")]

```

```{r creating_regularity, include=FALSE}
#'create a daily sequence from the min to the max date
day_seq = seq(as.Date(min(goose_time$time)),
              as.Date(max(goose_time$time)), by = "day")

#should be more than 3600 days, since this is 10 years
length(day_seq)

#'now reduce to only y-m-d if not already so

#day_seq = as.POSIXct(day_seq, format = "%Y-%m-%d")
#'now merge goose_aggregate df with time seq

#'convert goose_aggregate$time to Date
#'oh dear, never thought i'd use as.Date!
goose_aggregate$time = as.Date(goose_aggregate$time)

#'merge the day sequence and the aggregated goose data
#'take care to keep empty places where there are no observations
goose_time_merge = merge(as.data.frame(day_seq),
                         goose_aggregate, by.x = "day_seq",
                         by.y = "time", all.x = T)

#'how many complete cases? same as the number of aggregated records
sum(complete.cases(goose_time_merge))

#'set all values where no records were taken to 0
#'not very realistic in the winter
#goose_time_merge[is.na(goose_time_merge)] = 0

```

```{r assign_breeding_year, include=FALSE}
#'the breeding year is assigned based on the month of the day sequence. months 1:7 are assigned to the previous breeding year.
library(lubridate)
goose_time_merge$Breeding_year = ifelse(month(goose_time_merge$day_seq) %in% c(1:7),
       year(goose_time_merge$day_seq)-1,
       year(goose_time_merge$day_seq))
```

```{r assign_zones_goose_time, include=FALSE}
#'use the same proc as before
goose_time_merge$zone = ifelse(goose_time_merge$Group.2 %in% c("DU","KLE","RG","WES","WG"),
       "Rhinelands",
       ifelse(goose_time_merge$Group.2 %in% c("LER","DR","GR"),
              "East Frisia",
       ifelse(goose_time_merge$Group.2 %in% c("FR","FL","NH"),
              "IJsselmeer", 
              ifelse(goose_time_merge$Group.2 %in% c("ZL","ZH"),
                     "Southwest", "Other"))))

```


```{r melt_goose_time_merge, eval = FALSE, fig.height=10, fig.width=15, warning=FALSE}
#'melt data to get flocksize and juvprop as idvars
library(reshape)
#goose_time_merge$zone = as.factor(goose_time_merge$zone)
goose_time_merge_melt = melt(goose_time_merge[,c(1:6)],
                             id.vars = c("zone","day_seq"))
```

```{r trend_flock_juv_global, fig.height=6, fig.cap= "Global flock size trend follows the lemming cycle.", warning=FALSE, message=FALSE}
#'auto(gam) smoothing on flock size data using ggplot
ggplot(data = goose_time_merge)+
 geom_smooth(aes(x = day_seq, y = Total_flock),
           method = "auto", lty = 1)+
  geom_smooth(aes(x = day_seq, y = Total_flock),
              method = "lm", col = 2)+
  
  labs(list(x = "Time", y = "Flock size & Juvenile % * 10", title = "Smoothed flock size & juvenile % trends over time, global data"))+ theme_minimal()
```

# Zonal flock size trend

```{r trend_flock_juv_zonal, fig.height=6, fig.cap= "Rhinelands drive the global flock size trend. GAM smoothing: blue, linear trend: red.",warning=FALSE, message=FALSE}
#'auto(gam) smoothing on flock size data using ggplot
ggplot(data = goose_time_merge)+
 geom_smooth(aes(x = day_seq, y = Total_flock),
           method = "auto", lty = 1,size = 0.5)+
  geom_smooth(aes(x = day_seq, y = Total_flock),
              method = "lm", col = 2,size = 0.5)+
labs(list(x = "Time", y = "Flock size", title = "Smoothed flock size trends over time, zonal data"))+ theme_minimal()+ylim(0,2000)+
  facet_wrap(~zone, scales = "free_y")
```

# Global juvenile % trend

```{r trend_juv_global, fig.height=6, fig.cap= "Global juvenile % trend also follows lemming cycle. GAM smoothing, blue; linear trend, red.", warning=FALSE, message = FALSE}
#'auto(gam) smoothing on flock size data using ggplot
ggplot(data = goose_time_merge)+
# geom_point(data = goose_time_merge,
 #           aes(x = day_seq, y = Total_flock),
  #         col = "grey20", size = 0.5)+
 geom_smooth(aes(x = day_seq, y = Perc.JV),
              method = "auto", size = 0.5)+
  geom_smooth(aes(x = day_seq, y = Perc.JV),
              method = "lm", col = 2, size = 0.5)+
  #geom_smooth(aes(x = day_seq, y = Total_flock),
   #           method = "auto", col = 2, size = 0.5)+
  labs(list(x = "Time", y = "Juvenile %", title = "GAM smoothed juvenile % trends over time, global data"))+ theme_minimal()
 #facet_wrap(~zone, scales = "free_y",
            #ncol = 2)
```

# Zonal juvenile % trend

```{r trend_juv_zonal, fig.height=6, fig.cap= "Zonal juvenile % trends are similar.", warning=FALSE, message=FALSE}
#'auto(gam) smoothing on flock size data using ggplot
ggplot(data = goose_time_merge)+
# geom_point(data = goose_time_merge,
 #           aes(x = day_seq, y = Total_flock),
  #         col = "grey20", size = 0.5)+
 geom_smooth(aes(x = day_seq, y = Perc.JV),
              method = "auto", size = 0.5)+
  geom_smooth(aes(x = day_seq, y = Perc.JV),
              method = "lm", col = 2, size = 0.5)+
  #geom_smooth(aes(x = day_seq, y = Total_flock),
   #           method = "auto", col = 2, size = 0.5)+
  labs(list(x = "Time", y = "Juvenile %", title = "GAM smoothed juvenile % trends over time, zonal data"))+ theme_minimal()+
 facet_wrap(~zone, scales = "fixed",
            ncol = 2)
```

# Global flock size within years

```{r mean_juvprop_year, include=FALSE}
library(plyr)

goose_means = ddply(goose_aggregate, "Breeding_year",summarize,
                    mean_jprop = mean(Perc.JV),
                    mean_flock = mean(Total_flock))

```

```{r trend_flock_yearly, fig.height = 5, fig.cap= "Global flock size trend within years is unrelated to lemming cycle. Loess smoothing, blue; linear trend, red.", warning=FALSE, message=FALSE}
#'auto(gam) smoothing on flock size data using ggplot
ggplot(data = goose_time_merge)+
 geom_smooth(aes(x = day_seq, y = Total_flock),
           method = "loess", lwd = 0.5)+
  geom_smooth(aes(x = day_seq, y = Total_flock),
              method = "lm", col = 2, lwd = 0.5)+
  labs(list(x = "Time", y = "Flock size", title = "Smoothed flock size trends within each breeding year, global data"))+ theme_minimal()+
  facet_wrap(~Breeding_year, scales = "free_x")
```

# Global juvenile % within years

```{r trend_juvprop_yearly, fig.height = 5, fig.width=10, fig.cap= "Global juvenile % rises over the winter. Loess smoothing, blue; linear trend, red; mean %, dotted line.", warning=FALSE}
#'auto(gam) smoothing on percjv data using ggplot
ggplot(data = goose_time_merge)+
 geom_smooth(aes(x = day_seq, y = Perc.JV),
           method = "loess", lwd = 0.5)+
  geom_smooth(aes(x = day_seq, y = Perc.JV),
              method = "glm", col = 2, lwd = 0.2)+
  geom_hline(aes(yintercept = mean_jprop), goose_means,
             lty = 3, lwd = 0.5)+
  labs(list(x = "Time", y = "Juvenile %", title = "Smoothed juvenile percentage trend within each breeding year, global data"))+ theme_minimal()+
  facet_wrap(~Breeding_year, scales = "free_x", ncol =4)
```

# Family size trend

```{r, include=FALSE}
#'load knitr
library(knitr)
library(ggplot2)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/")
```

```{r load data, include=FALSE}
#'load libs
library(readxl)
library(RColorBrewer)

#'import data
lt_geese = read_excel("~/git/thesis/Age-ratiodata-GWfG-toPratik.xlsx",
    sheet = "Plain_table", col_types = c("text",
        "numeric", "numeric", "numeric",
        "numeric", "text", "text", "text",
        "text", "numeric", "text", "text",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "text", "text",
        "text"))
```

```{r reduce_data}
#'all records in the netherlands or nrw after than 2000

#'first keep only nl or nrw after 2000
study_site = lt_geese[lt_geese$Country %in% c("NL","NRW"),]

study_site = study_site[study_site$Breeding_year %in% c(2001:2011),]
```


```{r assign_time, include=FALSE}
#'fix missing days
study_site$Day = ifelse(is.na(study_site$Day),
                        15, study_site$Day)

#'use a time column of the posixct class
study_site$time = as.POSIXct(paste(study_site$Year,
                                   study_site$Month,study_site$Day),
                             format="%Y %m %d")
#'fix flock size
study_site$Total_flock = ifelse(is.na(study_site$Total_flock),
        ifelse(is.na(study_site$N_sampled),
               study_site$N_Adult+study_site$juvs,
               study_site$N_sampled),
                        study_site$Total_flock)

#'fix juvenile percentage
study_site$`Perc-JV` = ifelse(is.na(study_site$`Perc-JV`),
          study_site$juvs*100/study_site$Total_flock,
                        study_site$`Perc-JV`)

#'check for NAs
apply(study_site, 2, function(x){sum(is.na(x))})

#remove dates over May 2012
study_site = study_site[study_site$time < "2012-05-01",]

#'rename
geese = study_site
```

```{r assign_zones, include=FALSE}
#'assign zones
geese$zone = ifelse(geese$Region %in% c("DU","KLE","RG","WES","WG"),
       "Rhinelands",
       ifelse(geese$Region %in% c("LER","DR","GR"),
              "East Frisia",
       ifelse(geese$Region %in% c("FR","FL","NH"),
              "IJsselmeer",
              ifelse(geese$Region %in% c("ZL","ZH"),
                     "Southwest", "Other"))))
#'rename percjv
library(plyr)
geese = rename(geese, replace = c("Perc-JV" = "propjuv",
                                  "N_Juvenile" = "juvs"))

#'keep relevant columns
geese = geese[,c(2,7,14:29,33,34)]

#'count number of families
geese$fams = apply(geese[,c(8:17)], 1, function(x){sum(x, na.rm = T)})

#'subset
fams = geese[geese$fams > 0,]
```

```{r sum_fams_peryear_perzone, include=FALSE}
#'try to get a representation of the number of families of each size recorded per zone per year.
fam_count2 = ddply(fams[,c(1,8:17,20)], c("zone","Breeding_year"), numcolwise(sum, na.rm = T))

library(reshape)

#'then melt
fam_count_melt = melt(fam_count2, id.vars = c("zone","Breeding_year"))
```

```{r plot_fams_per_year_perzone_persize, fig.cap="Families of size *n* are distributed similarly across zones. Fam2 more in lemming-peak year (2005), less in crash years ('03, '08).", fig.height=5, fig.width=10, message=FALSE, warning=FALSE}
#'how many families of each size per zone per year
ggplot()+
  geom_col(data = fam_count_melt[fam_count_melt$Breeding_year %in% c(2003,2005,2008,2011) & fam_count_melt$zone %in% c("East Frisia", "IJsselmeer","Rhinelands"),],
                 aes(x = variable,
                     y = value,
                     fill = variable),col=1, lwd = 0.1)+
  scale_fill_brewer()+
  facet_grid(Breeding_year~zone, margins = F, scales = "free_y")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(list(x = "Family size",y = "Count",
            title = "Family size counts per zone per year"))+theme_minimal()
```

# Number of families ~ number of juveniles

```{r loglogfamsjuvs, fig.cap="Total families ~ juvenile count is a linear relationship on log-log axes.", fig.height=6, message=FALSE, warning=FALSE}
#'split by year alone
ggplot(data = fams[fams$Breeding_year %in% c(2003,2005,2008,2011) &
                     fams$zone %in% c("East Frisia","IJsselmeer","Rhinelands"),])+
  geom_point(aes(x = log(juvs), y = log(fams)),
             size = 0.5)+
  facet_grid(Breeding_year~zone)+theme_minimal()
```

# Predicting number of families

```{r lm_loglogfams_juvs, include=FALSE}
#'run an lm on log transformed data
fam_juvs_lm1 = lm(log(fams) ~ log(juvs), data = fams[fams$juvs >0,])

#'summarise it
summary(fam_juvs_lm1)

#coeffs
fam_juvs_lm1$coefficients
```

```{r scatterplot_lm1_fams_juvs, echo=FALSE, fig.cap="Model fit and data. Adj. R-squared = 0.83. Possible to get sum families from juvenile count.", fig.height=5, message=FALSE, warning=FALSE}
#'fams juvs scatter with fitted function

ggplot(data = fams, aes(x = log(juvs), y = log(fams)))+
  geom_point(size = 0.5, pch = 21)+
  labs(list(x = "ln(Juveniles)",  y = "ln(Number of families)",
            title = "Number of families ~ number of juveniles, log-log transformation"))+
  geom_smooth(method = "lm", lwd = 0.5, col = 2)+theme_minimal()
```

***

```{r compare_nls_lm_resids, echo=FALSE, fig.height=5, fig.cap="Linear model residual plot."}
#'plot it and the residuals plot of the nls model
plot(fam_juvs_lm1,1, main = "Residuals plot, log-log LM", cex = 0.5)
```