---
title: "Juvenile proportion GAM"
output:
  beamer_presentation: 
    colortheme: seahorse
    fonttheme: structurebold
    theme: Malmoe
classoption: aspectratio=1610
fontsize: 8pt
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(ggplot2)
library(lme4)
library(lubridate)
library(car)
library(broom)
library(gamm4)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")

#'load model object
load("goose_code012_gams.RData")
```

```{r read_data, eval=FALSE}
geese = read.csv("data.goose.clean.csv",row.names = 1)
geese$time = as.Date(geese$time)
#'assign month
geese$month = month(geese$time)
#'make percentages proportions
geese$propjuv = geese$propjuv/100

#'assign wintermonth
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]

#'source days since
source("days_since.r")

geese$days = days_since(geese$time)

#'source omega squared
source("mixed_mods_rsquared.r")
```

```{r bryr_days_zone_refs, eval=FALSE}
gamm01 = gamm4(propjuv ~ s(Breeding_year) + s(days) + s(lon, k=4), random = ~(1|Food_type) + (1|Observer) + (1|flocksize),
               data = geese, family = "binomial")
```

```{r summary_gamm01, eval=FALSE}
summary(gamm01$gam)

vis.gam(gamm01$gam, view = c("Breeding_year","days"), type = "response",
        theta = 15, color = "terrain", ticktype = "detailed")

summary(gamm01$mer)
```

# GAM as a mixed model

- GAMs can include smooths of factors while using a 'random effect' smoothing basis, making the GAM a mixed model

```{r gam02_refs, eval=FALSE}
#'gam with random effects included as smooths, with the smoothing basis as re, random effect
gam02 = gam(propjuv ~ ti(Breeding_year) + ti(days) + ti(Breeding_year, days) + s(lon, k=4) + s(zone, bs="re") + s(Observer, bs="re") + s(Food_type, bs = "re") + s(flocksize, bs = "re"),
            data = geese, family = "binomial")
```

- Formula:
```{r gam02_call, echo=FALSE}
s1 = summary(gam02)
(s1call = s1$formula)
```

- Model has a high AIC score: ```r AIC(gam02)```

# Model summary

- Breeding year is the only significant fixed effect, flocksize the only significant random effect.

```{r pred_effs}
s1$s.table
```

# Visualising trend

```{r visualise_gam02, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Proportion depends on lemming years, and rises across longitudes through the winter."}
par(mfrow = c(1,2))
vis.gam(gam02, type = "response", color = "terrain",
        view = c("Breeding_year","days"),
        ticktype = "detailed", plot.type = "contour",
        theta = 10, main = "juvenile proportion")

vis.gam(gam02, type = "response", color = "terrain",
        view = c("lon","days"),
        ticktype = "detailed", plot.type = "contour",
        theta = 10, main = "juvenile proportion")
par(mfrow = c(1,1))
```


```{r bryr_days_zone_refs02, eval=FALSE}
gamm02 = gamm(propjuv ~ ti(Breeding_year) + ti(days) + ti(Breeding_year, days) + s(lon, k=4), random = list(Food_type=~1, Observer=~1, flocksize = ~1), data = geese, family = "binomial")
```

```{r summary_gamm_year_days_zone, eval=FALSE}
#'summary
summary(gamm02$gam)

#'aic
AIC(gamm03$gam)
```

```{r visualise, echo=FALSE, message=FALSE, warning=FALSE}
par(mfrow = c(1,2))
vis.gam(gamm02$gam, type = "response", theta = 10, phi = 25,
        ticktype ="detailed", color = "terrain", plot.type = "contour",
        main = "juvenile proportion")

vis.gam(gamm02$gam, type = "response", theta = 10, phi = 25,
        ticktype ="detailed", color = "terrain", plot.type = "contour",
        main = "juvenile proportion", view = c("days","lon"))
par(mfrow = c(1,1))
```

