---
title: "Migration data"
editor_options: 
  chunk_output_type: console
---
# Assign activity levels to data

```{r, include=FALSE}
#'load knitr
library(knitr)
library(lubridate)
library(dplyr)
library(readxl)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r import_data}
spring = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 2)
autumn = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 3)

#'remove NAs
spring = spring[complete.cases(spring),]
autumn = autumn[complete.cases(autumn),]
```

```{r classify_data}
#'get percentiles and quantiles for count values
spring2 = spring %>% group_by(Year) %>% mutate(percentile = findInterval(NumberperHour, quantile(NumberperHour, probs=seq(0,1,0.01), include.lowest = T)),
   quantile = findInterval(NumberperHour, quantile(NumberperHour, 1:4/4, include.lowest = T)))

#'same for autumn
autumn2 = autumn %>% group_by(Year) %>% mutate(percentile = findInterval(NumberperHour,                 quantile(NumberperHour, probs=seq(0,1,0.01), include.lowest = T)),
   quantile = findInterval(NumberperHour, quantile(NumberperHour, 1:4/4, include.lowest = T)))
```

```{r merge_data}
#'merge classified dfs to originals
spring = merge(spring, spring2[,c("Date","percentile","quantile")], by= "Date", all.x = T)

autumn = merge(autumn, autumn2[,c("Date","percentile","quantile")], by= "Date", all.x = T)

#'set all NAs to zero. these are true zeroes.
spring[,c("percentile","quantile")] = do.call(data.frame, lapply(spring[,c("percentile","quantile")], function(y) {replace(y, is.na(y), 0)}))

autumn[,c("percentile","quantile")] = do.call(data.frame, lapply(autumn[,c("percentile","quantile")], function(y) {replace(y, is.na(y), 0)}))

#'rbind
a1 = rbind(spring, autumn)

#assign season
a1$season = ifelse(a1$Month > 6, "autumn","spring")

#'assign bryear
a1$bryear = ifelse(a1$Month > 6, a1$Year, a1$Year-1)
```

```{r merge_obs_dateseq}
#'create a sequence from 2000 to april 2017
#a = data.frame(Date = round_date(seq.POSIXt(as.POSIXct("2000-01-01"),as.POSIXct("2017-04-01"),"day"), "day"))


#' convert to character
#a$Date = as.character(a$Date)
#a1$Date = as.character(a1$Date)

#'merge the observations with the date sequence
#a = left_join(a, a1, by = "Date")
#a$Date = as.POSIXct(a$Date)

#'assign activity
b = data.frame(quantile = 0:4, activity = c("none","low","medium","high","max"))

#'merge with a
a1 = merge(a1, b, by="quantile", all.x = T)

library(reshape)
a1 = sort_df(a1, vars = "Date")
```

```{r vis, fig.height=12, fig.width = 15, eval = FALSE}
library(ggplot2)
png("~/git/thesis/migration_timing.png", width = 4800, height = 3200, res = 300)
ggplot(a1)+
  geom_line(aes(x=Date, y = NumberperHour))+
  facet_wrap(~Year, scales = "free")+
  labs(list(title = "No./hr ~ Date"))+
  theme_bw()+
  theme(strip.background = element_blank(), strip.placement = "none")
dev.off()
```


# Where are the peaks?

```{r mean_maxs}
#'find the first or last date, for autumn and spring respectively, for greater than 90th percentile values of activity in each year and each season

#'get peaks by season by bryear
peaks = a1 %>% group_by(bryear, season) %>% filter(percentile > 90) %>% summarise(peak = if(season == "spring") as.character(last(Date)) else as.character(first(Date)))

library(reshape2)
peaks = dcast(peaks, bryear ~ season, value.var = "peak")

peaks$durwinter = as.numeric(abs(difftime(peaks$autumn, peaks$spring)))

#'add peaks to df
#a1 = merge(a1, peaks, by = c("bryear"))

#'get time to peak from each record
#a1$t_since_in = as.numeric(abs(difftime(a1$Date, a1$autumn.x, units = "days")))

#a1$t_to_out = as.numeric(abs(difftime(a1$Date, a1$spring.x, units = "days")))
```

```{r plot_peaks}
#'plot peaks as a line
library(ggplot2)
png("goose_flight_intensity.png", width = 1600, height = 1600, res = 400)
ggplot(a1 %>% filter(bryear %in% c(2001, 2005, 2010, 2016)))+
  geom_line(aes(x=Date, y = NumberperHour))+
  
  geom_hline(data = a1 %>% filter(bryear %in% c(2001, 2005, 2010, 2016)) %>% filter(percentile >= 90) %>% group_by(bryear) %>% mutate(num = mean(NumberperHour)), aes(yintercept = num), col = colb, lty = 2)+
  
  geom_rect(data = peaks %>% filter(bryear %in% c(2001, 2005, 2010, 2016)) %>% group_by(bryear), aes(xmin = as.POSIXct(autumn), xmax = as.POSIXct(spring), ymin = 600, ymax = 650, group = bryear), fill = "lightblue", col = "lightblue", lty = 1, alpha = 0.5)+
  geom_text(data = peaks %>% filter(bryear %in% c(2001, 2005, 2010, 2016)) %>% group_by(bryear), aes(x = as.POSIXct(autumn)+durwinter/2*864e2, y = 625, label = durwinter, group = bryear), size = 3)+
  facet_wrap(~bryear, scales = "free_x")+
  labs(list(title = NULL, y = "Geese per observ. time (n/hr)"))+
  theme_bw()+theme(axis.text.x = element_text(size = 8, angle = 20, hjust = 1), strip.background = element_blank())+ylim(NA, 700)
dev.off()
```

```{r}
png(filename = "durwinters.png", width = 1600, height = 1600, res = 300)
ggplot()+
  geom_line(data = peaks, aes(x = bryear, y = durwinter), lty = 1)+
  geom_hline(data = peaks, aes(yintercept = mean(durwinter, na.rm = T)), col = colb, lty = 2)+
  geom_point(data = peaks, aes(x = bryear, y = durwinter), shape = 21, size = 3, fill = cola, col = "white")+
  theme_bw()+g1+labs(list(x = "Breeding year", y = "Goose winter residence (days)"))

dev.off()
```

```{r}
source("ggplot.opts.r")
```


```{r write_csv}
write.csv(a1, "migration_data.csv")
```


# Where are the sites?

```{r plot, fig.height=10, fig.width=10}
#'read in the site data
spring.sites = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 4)
spring.sites$season = "spring"
autumn.sites = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 5)
autumn.sites$season = "autumn"
migration.sites = rbind(spring.sites, autumn.sites)

a = table(migration.sites$Name_site, migration.sites$season)

sum(apply(a, 1, function(x){sum(x)>1}))

#'map it, get nl
library(maps); library(ggplot2)
nl = map_data("world", region = "Netherlands")

#'plot sites
ggplot()+
  geom_polygon(data=nl, aes(x=long, y=lat, group = group), fill = "grey90")+
  geom_point(data = migration.sites, aes(x=Lon, y=Lat, shape = season, col = season), size = 4)+
  scale_shape_manual(values = c(4,20))+
  theme_bw()
```

```{r}
migration.sites[duplicated(migration.sites[,c("Lon","Lat")]),]$season = "both"
migration.sites = migration.sites %>% arrange(season)
migration.sites = migration.sites[!duplicated(migration.sites[,c("Lon","Lat")]),]
```

