---
title: Weather data
---

# Get NL weather data

```{r load_libs}
library(readr); library(plyr); library(dplyr); library(purrr);library(purrrlyr);library(data.table);library(lubridate)
```

```{r load_sites}
library(readr)
knmi_sites <- read_csv("~/git/family_sizes_geese_2018/code/knmi_sites.txt")
```


```{r load_data}
nlweather = read_csv("~/git/family_sizes_geese_2018/code/holland_weather.txt", 
     col_types = cols(date = col_date(format = "%Y%m%d"), 
         mintemp = col_number(), ppt = col_number(), 
        windspeed = col_number()))

#'div temp and windspeed by 10
nlweather$mintemp = nlweather$mintemp/10
nlweather$windspeed = nlweather$windspeed/10

#'filter out station 209 and 215, have few records, 209 is missing entirely

nlweather = nlweather %>% filter(station != 209, station != 215)
#'set ppt of -1 to 0.01
nlweather$ppt = ifelse(nlweather$ppt < 0, 0.01, nlweather$ppt)
```

# Germany weather

```{r}
deweather <- read_csv("~/git/family_sizes_geese_2018/code/weather_munster.csv", 
   col_types = cols(date = col_date(format = "%Y%m%d")))
```

# Rbind weather frames

```{r}
weather = rbind(nlweather, deweather)
```


# Load data

```{r load_data}
source("dataprep.R")
```

```{r nearest_stn}
#'get unique family sites
famsites = fams.expand %>% group_by(lookup) %>% summarise(first(lon), first(lat))

#'get unique flock sites
flocksites = geese %>% group_by(lookup) %>% summarise(lon = first(lon), lat = first(lat))
```

```{r fam_temp_dists}
library(geosphere)

#'matrix of distances
flock_stns = apply(flocksites[,c("lon","lat")], 1, function(x){distVincentyEllipsoid(p1 = x, p2 = knmi_sites[,c("lon","lat")])})/1000

#'which station is nearest?
stn.near = data.frame(lookup = flocksites[,c("lookup")], 
               station = knmi_sites[apply(flock_stns, 2, which.min),"station"])

#'mean distances
mean(apply(flock_stns, 2, min))


#'for geese.org data
gorgstns = apply(geeseorg[,c("lon","lat")],1, function(x){distVincentyEllipsoid(p1 = x, p2 = knmi_sites[,c("lon","lat")])})/1000

geeseorg$stn = knmi_sites[apply(gorgstns, 2, which.min),"station"]$station


```

```{r merge_data}
#'fams data
fams.expand = merge(fams.expand, stn.near, by = "lookup", all.x = T)
fams.expand = merge(fams.expand, nlweather, by.x = c("station","time"), by.y = c("station","date"), all.x = T)

#'fams in flocks
fams = merge(fams, stn.near, by = "lookup", all.x = T)
fams = merge(fams, nlweather, by.x = c("station","time"), by.y = c("station","date"), all.x = T)


#'flock data
geese = merge(geese, stn.near, by = "lookup", all.x = T)
geese = merge(geese, nlweather, by.x = c("station","time"), by.y = c("station","date"), all.x = T)

#'geesorg data
geeseorg = merge(geeseorg, nlweather, by.x = c("stn", "date"), by.y = c("station","date"), all.x = T)
```

```{r nfams_temp}
library(mgcv)
#'number of families in flocks 
nfams.tempmod = bam(fams ~ s(flocksize) + distkol + s(t_since_in, k = 4) + mintemp + ppt + windspeed + s(Breeding_year, bs = "re") + s(Observer, bs = "re") + s(Food_type, bs = "re"), data = fams, family = "poisson")

nfamspred = predict(nfams.tempmod, type = "response", terms = "s(flocksize)", newdata = fams, se.fit = T)

summary(nfams.tempmod)

pdf(file = "~/git/family_sizes_geese_2018/texts/nfamsclim.pdf", width = 5, height = 5, title = "nfamsclim")
vis.gam(nfams.tempmod, view = c("mintemp", "ppt"), type = "response", theta = 30, color = "cm", zlab = "N families", xlab = "Min. temp", ylab = "Precipitation")
dev.off()

visreg(nfams.tempmod, "ppt", scale = "response")
```

```{r flocksize_temp}
flock.tempmod = glmer(flocksize ~ sqrt(distkol) + mintemp + sqrt(ppt) + windspeed + log(t_since_in) + (1|Observer) + (1|Food_type)+ (1|Breeding_year), data = geese, family = "poisson")

summary(flock.tempmod)

pdf(file = "~/git/family_sizes_geese_2018/texts/flockclim.pdf", width = 5, height = 5, title = "flockclim")
vis.gam(flock.tempmod, view = c("mintemp", "ppt"), type = "response", theta = 45, color = "cm", zlab = "Flocksize", xlab = "Min. temp", ylab = "Precipitation")
dev.off()

visreg(flock.tempmod, "mintemp", scale = "response")
```

```{r juvsclim}
save(nfams.tempmod, flock.tempmod, file = "climmods.rdata")
```

