---
title: Exporting fam tracks w/o bursts
---

```{r set_env}
#'load knitr
library(knitr);library(lubridate);library(broom)

library(move);library(RCurl);library(bitops)

library(plyr);library(dplyr);library(rgdal);library(spacetime)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r load_data}
load("fams2014.nobursts.rdata");load("fams2016.nobursts.rdata")
```

```{r make_spatial}
#'fams2014
fams2014sp = lapply(fams2014.5, function(x){lapply(x, function(y){ y = SpatialPointsDataFrame(coords = y[,c("lon","lat")], data = y, proj4string = CRS("+init=epsg:4326"))})})

#fams2016
fams2016sp = lapply(fams2016.4, function(x){lapply(x, function(y){ y = SpatialPointsDataFrame(coords = y[,c("lon","lat")], data = y, proj4string = CRS("+init=epsg:4326"))})})

```

```{r plottest}
library(maps)
plot(fams2016sp[[1]][[1]])
map("world",add=T)
```

```{r assign_indiv_names}
library(maptools);library(stringr)

#'assign name column again...
#'for families in 2014
for(i in 1:length(fams2014sp)){
  for(j in 1:length(fams2014sp[[i]])){
    fams2014sp[[i]][[j]]$name = names(fams2014sp[[i]])[j]
  }
}

#'for families in 2016
for(i in 1:length(fams2016sp)){
  for(j in 1:length(fams2016sp[[i]])){
    fams2016sp[[i]][[j]]$name = names(fams2016sp[[i]])[j]
  }
}

#'get oldfamnames
oldfamnames = names(fams2014sp)
```

```{r export_kml_2014}
#'write families 2014 to kml
for(i in 1:length(fams2014sp)){

kml_open(paste0(oldfamnames[i],".kml"))
#'KML file opened for writing...
for(j in 1:length(fams2014sp[[i]])){
   kml_layer.SpatialPoints(obj=fams2014sp[[i]][[j]], points_names = fams2014sp[[i]][[j]]$name, shape = "Circle", colour = ("Yellow"))
}
kml_close(paste0(oldfamnames[i],".kml"))
}
```

```{r export_kml_2016}
#'get new fam names

names(fams2016sp)[4] = "Wo"
newfamnames = names(fams2016sp)
#'write families 2016 to kml

for(i in 1:length(fams2016sp)){

kml_open(paste0(newfamnames[i],".kml"))
#'KML file opened for writing...
for(j in 1:length(fams2016sp[[i]])){
   kml_layer.SpatialPoints(obj=fams2016sp[[i]][[j]], points_names = fams2016sp[[i]][[j]]$name, shape = "Circle", colour = ("Yellow"))
}
kml_close(paste0(newfamnames[i],".kml"))
}
```


