---
title: thesis model plots
---

```{r set_env, message=FALSE, echo=FALSE, warning=FALSE}
#'load knitr
library(knitr);library(plyr);library(dplyr);library(data.table);library(purrr);library(ggplot2)

#'load model libs
library(mgcv);library(gamm4)
#'load variogram libraries
library(sp);library(gstat);library(visreg)

#'suppress all code output but run code
opts_chunk$set(eval = FALSE)
opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE, eval=TRUE}
source("dataprep.R")
load("goosemods_pres.RData")
load("distmods.Rdata")
load("fsize_coords.rdata")

#'define ggplot axis and grid options
a = theme(panel.grid.minor = element_blank())
b1 = theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

# Distance to Kolguyev ~ family size

```{r distkol_fams1, message=FALSE, echo=FALSE, warning=FALSE}
#'get model response for lon
vis.distmod1 = visreg(distmod, "famsize", scale = "response", plot = F)

out.distmod1 = vis.distmod1$fit
```

```{r distkol_fam1, message=FALSE, echo=FALSE, warning=FALSE}
#'get model response for lon
vis.distmod1l = visreg(distmod_late, "famsize", scale = "response", plot = F)

out.distmod1l = vis.distmod1l$fit
```

```{r distkol_fam2, message=FALSE, echo=FALSE, warning=FALSE}
#'get model response for lon
vis.distmod2 = visreg(distmod2, "famsize", scale = "response", plot = F)

out.distmod2 = vis.distmod2$fit
```

```{r distkol_fam2l, message=FALSE, echo=FALSE, warning=FALSE}
#'get model response for lon
vis.distmod2l = visreg(distmod2_late, "famsize", scale = "response", plot = F)

out.distmod2l = vis.distmod2l$fit
```

## Plot

```{r export_distkol_fams1, eval = FALSE}
pdf(file = "~/git/thesis/texts/dist_fam.pdf", height = 3, width = 4, title = "distance_famsize")

#'red:early, triangle:geese.org, dotted:geese.org

#'plot
ggplot()+

geom_line(data = out.distmod1, aes(x = famsize, y = visregFit), col = "indianred1", lty = 1)+
  
geom_line(data = out.distmod1l, aes(x = famsize, y = visregFit), col = "royalblue", lty = 1)+

geom_line(data = out.distmod2 %>% filter(famsize <=10), aes(x = famsize, y = visregFit), col = "indianred1", lty = 2)+

geom_line(data = out.distmod2l, aes(x = famsize, y = visregFit), col = "royalblue", lty = 2)+
  
geom_point(data = fams.expand.sub %>% filter(t_since_in < 60) %>% dplyr::select(famsize, distkol) %>% 
                slice_rows("famsize") %>% dmap(median), aes(x = famsize, y = distkol), col = "indianred1", size = 3, pch = 16)+

geom_point(data = fams.expand.sub %>% filter(t_since_in > 60) %>% dplyr::select(famsize, distkol) %>% slice_rows("famsize") %>% dmap(mean), aes(x = famsize, y = distkol), col = "royalblue", size = 3, pch = 16)+

geom_point(data = geeseorg %>% filter(t_since_in < 60, famsize <=10) %>% dplyr::select(famsize, distkol) %>%
                slice_rows("famsize") %>% dmap(mean), aes(x = famsize, y = distkol), col = "indianred1", size = 3, pch = 17)+

geom_point(data = geeseorg %>% filter(t_since_in > 60) %>% dplyr::select(famsize, distkol) %>% slice_rows("famsize") %>% dmap(mean), aes(x = famsize, y = distkol), col = "royalblue", size = 3, pch = 17)+

labs(list(x = "N juveniles", y = "Km. from Kolguyev Island"))+
  ylim(2700, 3100)+
  xlim(0,10)+ scale_x_continuous(breaks = 0:10)+
  theme_bw()+a
dev.off()
```

# Family size ~ time

```{r modresponse_fam_time}
#'get model response for t_since_in
vis.mod03.time = visreg(mod03, "t_since_in", scale = "response", plot = F)

#'make data frame
vis.mod03.time.data = vis.mod03.time$fit

#'add t_since_in to splits data
splits$time = as.Date(splits$time)

#'merge mig.red and splits
splits = merge(splits, mig.red, by.x = "time", by.y = "Date")
```

```{r pred_famsize-time_gorg}
vis.famsize.time.gorg = visreg(mod03.gorg, "t_since_in", scale = "response",plot = F)

vis.famsize.time.gorg.data = vis.famsize.time.gorg$fit

vis.famsize.time.gorg.s = visreg(mod03.gorg.s, "t_since_in", scale = "response", plot = F)

vis.famsize.time.gorg.s.data = vis.famsize.time.gorg.s$fit

```

## plot

```{r export_fam_time, warning=FALSE, message=FALSE}
pdf(file = "~/git/thesis/texts/fam_time.pdf", height = 3, width = 4, title = "famsize_time")

ggplot()+

  geom_point(data = fams.expand.sub %>% group_by(round(t_since_in)) %>% dmap(mean), aes(x = t_since_in, y = famsize), col = "indianred1", size =0.5)+
  
  geom_point(data = geeseorg %>% group_by(round(t_since_in)) %>% dmap(mean), aes(x = t_since_in, y = famsize), col = "royalblue", size =0.5)+
  
  geom_point(data = geeseorg %>% filter(famsize > 0) %>% group_by(round(t_since_in)) %>% dmap(mean), aes(x = t_since_in, y = famsize), col = "black", size =0.5)+
  
  
  geom_line(data = vis.mod03.time.data, aes(x = t_since_in, y = visregFit), size = 0.8, col = "indianred1")+
  
  geom_line(data = vis.famsize.time.gorg.data, aes(x = t_since_in, y = visregFit), size = 0.8, col = "royalblue")+
  
  geom_line(data = vis.famsize.time.gorg.s.data, aes(x = t_since_in, y = visregFit), size = 0.8, col = "black")+
  
  geom_path(data = splits %>% filter(event %in% c("Start", "Split")), aes(x = t_since_in, y = fsize, group = fam), arrow = arrow(length = unit(0.02, "npc"), type = "closed"), lty = 1, lwd = 0.2, col = "grey30")+
  
 geom_text(data = splits %>% filter(fam %in% c("Ev","Wo","Ha","Na","Ti","Ma","Ro","An","Jo"), event == "Start"), aes(x=t_since_in, y = fsize, label = substr(fam,1,1), angle = 0), hjust = 1, vjust = 0, size = 3)+
  
  labs(list(x = "Days since arrival", y = "Juveniles in family"))+ 
  ylim(0,8)+ xlim(0,180)+
  theme_bw()+a

dev.off()
```

# Family size ~ p.index

```{r pred_famsize_pindex}
vis.famsize.pred = visreg(mod03, "p.index", scale = "response", plot = F)

vis.famsize.pred.data = vis.famsize.pred$fit

vis.famsize.gorg.pred = visreg(mod03.gorg, "p.index", scale = "response", plot = F)

vis.famsize.gorg.pred.data = vis.famsize.gorg.pred$fit

vis.famsize.gorg.s.pred = visreg(mod03.gorg.s, "p.index", scale = "response", plot = F)

vis.famsize.gorg.s.pred.data = vis.famsize.gorg.s.pred$fit
```

```{r plot_famsize_pred}
pdf(file = "~/git/thesis/texts/fam_predation.pdf", height = 3, width = 4, title = "distance_famsize")

ggplot()+
  geom_point(data = geeseorg %>% group_by(p.index) %>% summarise(famsize=mean(famsize, na.rm = T)), aes(x = p.index, y = famsize), size = 3, pch = 17, col = "royalblue")+

   geom_point(data = geeseorg %>% filter(famsize > 0) %>% group_by(p.index) %>% summarise(famsize = mean(famsize, na.rm = T)), aes(x = p.index, y = famsize), size = 3, pch = 17, col = "grey10")+
   
  geom_point(data = fams.expand.sub %>% group_by(p.index) %>% summarise(famsize = mean(famsize, na.rm = T)), aes(x = p.index, y = famsize), size = 3,col="indianred1")+
  
  #'dashed line, families in flocks
geom_line(data = vis.famsize.pred.data, aes(x = p.index, y = visregFit), lty = 1, col = "indianred1")+
  
  geom_line(data = vis.famsize.gorg.pred.data, aes(x = p.index, y = visregFit), col = "royalblue")+
  
geom_line(data = vis.famsize.gorg.s.pred.data, aes(x = p.index, y = visregFit), col = "grey10")+

  #geom_text(aes(x = 1.8, y = c(2, 1.5, 0.5), label = c("1","2","3")))+
  
labs(list(x = "Predation index", y = "Mean juveniles per family"))+
  theme_bw()+a

dev.off()
```

## Grid plot

```{r}
pdf(file = "~/git/thesis/texts/fam_trends.pdf", height = 4, width = 8, title = "fam_trends")
grid.arrange(p2,p3, ncol = 2)
dev.off()
```


# Flocksize ~ distkol

```{r model_pred_flockmod}
#'get model pred
vis.flockmod = visreg(flockmod, "distkol", scale = "response", plot = F)

vis.flockmod.data = vis.flockmod$fit
```

```{r export_flock_lon_plot}
pdf(file = "~/git/thesis/texts/flock_dist.pdf", width = 4, height = 3, title = "flock_dist")
ggplot()+
  geom_point(data = geese %>% slice_rows("lookup") %>% dmap(mean), aes(x = distkol, y = flocksize), size = 3, pch = 1, col = "grey50")+
  
  geom_line(data = vis.flockmod.data, aes(x = distkol, y = visregFit), size = 1, col = "grey10")+
  ylim(0,3000)+
  labs(list(x = "Km. from Kolguyev", y = "Flock size"))+
  theme_bw()+a

dev.off()
```

# Juvenile % ~ time

```{r pred_gamjuvs_time}
vis.juvs.time = visreg(modjuvs, "t_since_in", plot = T, scale = "response", type = "conditional", breaks = 20)

vis.juvs.time.data = vis.juvs.time$fit
```

```{r}
pdf(file = "~/git/thesis/texts/juvprop_time.pdf", width = 4, height =3)

ggplot()+
  #geom_smooth(data = geese %>% dplyr::select(month, t_since_in, propjuv) %>%  group_by(t_since_in) %>% dmap(mean), aes(x = t_since_in, y = propjuv))+

  geom_ribbon(aes(x = geese$t_since_in, ymin = x$fit-1.96*x$se.fit, ymax = x$fit+1.96*x$se.fit), fill = "grey50")+
  
  geom_point(data = geese %>% dplyr::select(month, t_since_in, propjuv) %>%  group_by(t_since_in) %>% dmap(mean), aes(x = t_since_in, y = propjuv), size = 1, shape = 1, col = 1)+
  
  geom_smooth(aes(x = geese$t_since_in, y = x$fit), lwd = 1, col = 1)+
  
  #geom_line(data = vis.juvs.time.data, aes(x = t_since_in, y = visregFit), size = 1, col = 1)+
  labs(list(x = "Days since arrival", y = "Juvenile proportion"))+
  ylim(0,0.6)+
  theme_bw()+a

dev.off()
```

# Juvenile % ~ p.index

```{r}
vis.juvprop.pred = visreg(modjuvs, "p.index", scale = "response", plot = F)

vis.juvprop.pred.data = vis.juvprop.pred$fit
```

```{r}
png(file = "~/git/thesis/texts/juv_trends.png", width = 800, height = 800, title = "juv_trends")
vis.gam(modjuvs, view = c("p.index","t_since_in"), type = "response", plot.type = "contour", main = NULL, xlab = "Predation index", ylab = "Days since arrival", color = "gray", contour.col = c("grey10","grey90","grey90","grey90","grey90","grey10"))
dev.off()
```


```{r}
#postscript(file = "plot13juvprop_pred.eps", colormodel = "grey", horizontal = FALSE, onefile = FALSE, height = 4, width = 5)

ggplot()+
  geom_point(data = geese, aes(x=p.index, y = propjuv), size = 0.1)+
  geom_ribbon(data = vis.juvprop.pred.data, aes(x = p.index, ymin = visregLwr, ymax = visregUpr), fill= "grey90", alpha = 0.9)+
  geom_line(data = vis.juvprop.pred.data, aes(x = p.index, y = visregFit), size = 1, col=2)+
  labs(list(x = "Predation index", y = "Juvenile proportion", title = "d"))+
  geom_text(aes(x = 1.9, y = 0.7, label = "{chi}^2==0.021"), hjust = "inward", parse = T)+ylim(0,0.8)+
  theme_bw()+a

#dev.off()
```

# Flock size ~ p.index

```{r pred_flocksize_pindex}
vis.flocksize.pred = visreg(flockmod, "p.index", scale = "response", plot = F)

vis.flocksize.pred.data = vis.flocksize.pred$fit
```

```{r}
#postscript(file = "plot13flocksize_pred.eps", colormodel = "grey", horizontal = FALSE, onefile = FALSE, height = 4, width = 5)

p11 = ggplot()+
  geom_point(data = geese, aes(x = p.index, y = flocksize), size = 0.1)+
  geom_ribbon(data = vis.flocksize.pred.data, aes(x = p.index, ymin = visregLwr, ymax = visregUpr), fill= "grey90", alpha = 0.9)+
  geom_line(data = vis.flocksize.pred.data, aes(x = p.index, y = visregFit), size = 1, col = 2)+
  labs(list(x = NULL, y = "Flock size", title = "a"))+
  ylim(0,9e3)+
  geom_text(aes(x = 1.5, y = 8500, label = "{Omega[0]}^2==0.99"), hjust = "inward", parse = T)+
  theme_bw()+a

#dev.off()
```

# Number of families ~ time

```{r}
vis.nfams.time = visreg(famsmod, "t_since_in", scale = "response", plot = F)

vis.nfams.time.data = vis.nfams.time$fit
```

```{r}
pdf(file = "~/git/thesis/texts/nfams_time.pdf", width = 4, height = 3, title = "nfams_time")

ggplot()+
  geom_ribbon(data = vis.nfams.time.data, aes(x = t_since_in, ymin = visregLwr, ymax = visregUpr), fill= "grey50")+
  geom_point(data = fams %>% group_by(t_since_in) %>% dmap(mean), aes(x = t_since_in, y = fams), size = 3, shape = 1, col = "black")+
  geom_line(data = vis.nfams.time.data, aes(x = t_since_in, y = visregFit), size = 1)+
  labs(list(x = "Days since arrival", y = "Successful families in flock"))+
  theme_bw()+a

dev.off()
```

# Export plots
```{r}
save(p1,p2,p3,p4,p5,p6,p7,p8,p9, p10,p11, p12, file = "goose_dataplots.Rdata")
```

#Grid
```{r yr_month_heatmap, fig.fullwidth=TRUE, fig.height=6, fig.width=8, fig.cap= "Heatmap of samples in each month in each year between 2001 - 2011. Colour scale represents the number of records.", warning=FALSE, eval = TRUE}

library(gridExtra);library(ggplot2)

#'distance ~ fam size
pdf(file = "~/git/thesis/texts/dist_fsize.pdf")
grid.arrange(p1, p2, p3, p4)
dev.off()

#'family trends
pdf(file = "~/git/thesis/texts/fam_trends.pdf", height = 6, width = 8)
grid.arrange(p5, p6, p7, p8, ncol = 2)
dev.off()

#'flock trends
pdf(file = "~/git/thesis/texts/flock_trends.pdf", height = 6, width = 8)
grid.arrange(p9, p10, p11, p12, ncol = 2)
dev.off()
```

# Other plots

# Flocksize ~ time

* Significant effect, flocks are larger in the late winter

```{r model_pred_flockmod_time}
#'get model pred
vis.flockmod.days = visreg(flockmod, "t_since_in", scale = "response", plot = F)

vis.flockmod.days.data = vis.flockmod.days$fit

p6.res = vis.flockmod.days$res
```

```{r export_flock_time_plot}
#postscript(file = "plot06flocksize_days.eps", colormodel = "grey", horizontal = FALSE, onefile = FALSE, height = 4, width = 5)

#p8 = ggplot()+
  geom_point(data = geese, aes(x = t_since_in, y = flocksize), size = 0.1)+
  geom_ribbon(data = vis.flockmod.days.data, aes(x = t_since_in, ymin = visregLwr, ymax = visregUpr), fill = "grey90", alpha = 0.9)+
  geom_line(data = vis.flockmod.days.data, aes(x = t_since_in, y = visregFit), size = 1, col = 2)+
  labs(list(x = "Days since first arrivals", y = NULL, title = "b"))+
  ylim(0,5000)+
  theme_bw()+b

#dev.off()
```

# Number of families ~ distance

```{r pred_famsmod}
visfamsmod = visreg(famsmod, "distkol", plot = T, scale = "response")

visfamsmod.data = visfamsmod$fit
```

```{r plot_pred_famsmod}
pdf(file = "~/git/thesis/texts/nfams_dist.pdf", width = 5, height = 4, title = "nfams_dist")

ggplot()+
 geom_ribbon(data = visfamsmod.data, aes(x = distkol, ymin = visregLwr, ymax = visregUpr), fill = "grey50")+
  geom_point(data = fams2 %>% group_by(lookup) %>% dmap(mean), aes(x = distkol, y = fams), shape = 1, size = 3)+
  geom_line(data = visfamsmod.data, aes(x = distkol, y = visregFit), size = 1, col = 1)+
  labs(list(x = "Km. from Kolguyev Island", y = "Number of families"))+
  theme_bw()+a

dev.off()
```

# Number fams ~ flock size

```{r modpred_fam_flocksize}
visfamsmod2 = visreg(nfams.tempmod, "flocksize", scale = "response", plot = F)

visfamsmod.data2 = visfamsmod2$fit
```

```{r plot_mod}
pdf(file = "~/git/thesis/texts/nfams_flock.pdf", width = 4, height = 3, title = "nfams_flock")

ggplot()+
    geom_ribbon(aes(x = fams2$flocksize, ymin = nfamspred$fit-1.96*nfamspred$se.fit, ymax = nfamspred$fit+1.96*nfamspred$se.fit), fill = "grey50", na.rm = T)+
  
  geom_point(data = fams2 %>% group_by(mround(flocksize,10)) %>% dmap(mean), aes(x = flocksize, y = fams), shape = 1, size = 2, colour = 1)+
 geom_smooth(aes(x = fams2$flocksize, y = nfamspred$fit), lwd = 1, col = 1)+
  labs(list(x = "Flock size", y = "N successful families"))+
  ylim(0,200)+
  theme_bw()+a



dev.off()
```

# Juvenile % ~ flocksize

```{r pred_gamjuvs_lon}
vis.juvs.flock = visreg(modjuvs, "flocksize", scale = "response",plot = F)

vis.juvs.flock.data = vis.juvs.flock$fit
```

```{r}
mround <- function(x, base) {round(x/base)*base}
```


```{r}
pdf(file = "~/git/thesis/texts/jprop_flock.pdf", width = 4, height = 3, title = "juvprop_flocksize")

ggplot()+
  
 geom_ribbon(aes(x = geese$flocksize, ymin = y$fit-1.96*x$se.fit, ymax = y$fit+1.96*x$se.fit), fill = "grey50")+
  
   geom_point(data=geese %>% mutate(roundflock = mround(flocksize, 25)) %>% slice_rows("roundflock") %>% dmap(mean), aes(x = flocksize, y = propjuv), size = 2, col = 1, shape = 1)+
  
  geom_smooth(aes(x = geese$flocksize, y = x$fit), size = 1, col = 1, se = F)+
  labs(list(x = "Flock size", y = "Juvenile proportion"))+
  theme_bw()+a

dev.off()
```