---
title: Mapping goose families
---

```{r}
#'source r dataprep file
source("dataprep.R")
```

```{r}
library(sp);library(raster);library(rgdal);library(maptools);library(tmap)
library(RColorBrewer)
```

```{r load_data}
#'load shapefiles
admin = readOGR("vector/ne_10m_admin_0_boundary_lines_land.shp")

land = readOGR("vector/ne_10m_land.shp")
rivers = readOGR("vector/ne_10m_rivers_lake_centerlines.shp")
lakes = readOGR("vector/ne_10m_lakes.shp")

#'how many unique sites?
dim(fams[!duplicated(fams[,c("lon","lat")]),])

#'make point observation data spatial
fams.spatial = fams[!duplicated(fams[,"Site_name"]),]
coordinates(fams.spatial) = ~lon+lat

fams.spatial$cat = 1

#'for geese.org data
geeseorg.spatial = geeseorg
geeseorg.spatial = geeseorg.spatial[!duplicated(geeseorg.spatial[,c("lon","lat")]),]
coordinates(geeseorg.spatial) = ~lon+lat

#'tracked family sizes
load("fsize_coords.rdata")

#'set extent
e = extent(3.5,7.75,50.75,53.5)
```


```{r, eval=FALSE}
#'map migration tracking sites
library(readxl)
spring.sites = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 4)
spring.sites$season = "spring"
autumn.sites = read_excel("~/git/thesis/Migration_data.xlsx", sheet = 5)
autumn.sites$season = "autumn"
migration.sites = rbind(spring.sites, autumn.sites)

coordinates(migration.sites) = ~ Lon+Lat
```

# Sampling grid: geese.org

```{r sampling_grid}
#'make grid topology
g.topo = GridTopology(cellcentre.offset = bbox(e)[,1]+(c(0.05,0.05)/2), cellsize = c(0.05,0.05), cells.dim = ceiling(diff(t(bbox(e)))/c(0.05,0.05)))

#'make spatial polygons grid
geeseorg.grid = as.SpatialPolygons.GridTopology(g.topo, proj4string= crs(admin))

#'set crs of geese.org
crs(geeseorg.spatial) = crs(land)

#'read bryear off geese.org data
geeseorg.grid$breedyr = over(geeseorg.grid, geeseorg.spatial[2], fn = max)

#subset by NA
geeseorg.grid = geeseorg.grid[!is.na(geeseorg.grid$breedyr),]
```

```{r}
#'get splits and lines between splits
load("fsize_coords.rdata")

#'how many splits?
dim(splits %>% filter(event == "Split"))
```

# geese.org KDE

```{r}
library(adehabitat); library(adehabitatHR)
library(ks);library(Grid2Polygons)

#'ks is great for plots, not so much for making spatial objects
#kdegeese = kde(x= pos, compute.cont=TRUE)

#'use adehabitat HR
kernelgeese = kernelUD(geeseorg.spatial, h = "LSCV", grid = 1000)
kdegeese = getverticeshr(kernelgeese, percent = 99.9)
library(rgeos)
crs(kdegeese) = crs(land)

kdegeese2 = gIntersection(kdegeese, land, byid = TRUE, drop_lower_td = TRUE)
```


# Basic datamap

```{r map_sovon}
pdf(file = "~/git/thesis/texts/datamap.pdf")
#'map locations
tm_shape(land, bbox = e - c(0,0,-0.2,0))+
  tm_polygons(col = "white", border.col = "grey70", alpha = 0.7)+

tm_shape(kdegeese2)+
  tm_polygons(col = "grey90", alpha = 1, border.col = "grey70", border.alpha = 1)+
tm_shape(lakes)+
  tm_polygons(alpha = 1, col = "white", border.col = "grey40")+
tm_shape(rivers)+
  tm_lines(col = "grey40")+

tm_shape(fams.spatial)+
  tm_dots(col = "black", shape = 4, size = 0.3)+
  
tm_shape(splits2[splits2$event == "Split",])+
  tm_symbols(shape = "event", col = "indianred1", shapes = c(25, 4), size = 1, border.col = "grey10", showNA = F, shapeNA = NA, legend.shape.show = F)+

tm_format_NLD()+
tm_scale_bar(position = c("left","bottom"), breaks=c(0,25,50), size = 1)+

tm_layout(frame = TRUE)
dev.off()
```

# Plot families

```{r}
daycoords.spat = daycoords
coordinates(daycoords.spat)=~lon+lat
```

```{r, eval=FALSE}
#pdf(file = "families.pdf", width = 10, height = 10)
#'map locations
tm_shape(land, bbox = e - c(0,0,-0.5,0))+
  tm_polygons(col = "white", border.col = "grey70", alpha = 0.4)+
tm_shape(admin)+
  tm_lines(col = "grey70")+
tm_shape(rivers)+
  tm_lines(col = "lightblue")+
tm_shape(lakes)+
  tm_polygons(alpha = 0.5, col = "grey80", border.col = "grey70")+
tm_shape(daycoords.spat)+
  tm_dots(col = "fam", size = 0.5, alpha = 0.5, title = "Family")+
  
  tm_scale_bar(position = c("left","bottom"), breaks=c(0,25,50))+
  
  tm_format_NLD()+
  
  tm_layout(frame = T, title = "Goose families, 2013 - 2016")
#dev.off()
```

# Family sizes

```{r}
#'load and plot
load("fsize_coords.rdata")

pdf(file = "tracked_fams_change.pdf", width = 10, height = 10)
daycoords %>% filter(fam %in% c("Ev","Ha","Ti","Wo")) %>%
ggplot()+
  geom_path(aes(x=time, y=fsize, col = lon), size = 4)+
  scale_color_gradientn(colours = rev(gray.colors(6)))+
  facet_wrap(~fam, scales = "free")+
  labs(list(x = "Time",y = "Family size (incl. ads.)"))+
  theme_minimal()
dev.off()
```

