---
title: "Juvenile proportion linear models"
output:
  beamer_presentation: 
    colortheme: seahorse
    theme: Szeged
classoption: aspectratio=1610
fontsize: 8pt
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(ggplot2)
library(lme4)
library(lubridate)
library(car)
library(broom)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")

#'load models
load("goose_code010_glmers.RData")
```

```{r read_data, eval=FALSE}
geese = read.csv("data.goose.clean.csv",row.names = 1)
geese$time = as.Date(geese$time)
#'assign month
geese$month = month(geese$time)
#'make percentages proportions
geese$propjuv = geese$propjuv/100

#'assign wintermonth
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]
```

# Mixed models, nested random effects

- Model 2: ```propjuv ~ Breeding_year + winter_month + zone + (1|Food_type/Observer/flocksize)```

- Model 3: ```propjuv ~ Breeding_year + winter_month + zone + Breeding_year*zone + Breeding_year*winter_month + winter_month*zone + (1|Observer/Food_type/flocksize)```

```{r global glmm, eval=FALSE}
#'global model with bryr, month and zone as fixed effects and flocksize, observer and foodtype as random effects
glmm_propjuv01 = glmer(propjuv ~ 
                         Breeding_year+winter_month+zone
                         + (1|flocksize) + (1|Observer) + (1|Food_type),
                  data = geese, family = "binomial", na.action = na.omit)
```

```{r global_glmm02, eval=FALSE}
#'global model with bryr, month and zone as fixed effects and flocksize, observer and foodtype as nested random effects
glmm_propjuv02 = glmer(propjuv ~ 
                         Breeding_year+winter_month+zone+
                         (1|Food_type/Observer/flocksize),
                  data = geese, family = "binomial", na.action = na.omit)

```

```{r global_glmm03, eval=FALSE}
#'global model with bryr, month and zone, and bryr*zone, bryr*month, month*zone as fixed effects and flocksize, observer and foodtype as random effects
glmm_propjuv03 = glmer(propjuv ~ 
                         Breeding_year+winter_month+zone+
                         Breeding_year*zone + Breeding_year*winter_month +
                         winter_month*zone +
                         (1|Observer/Food_type/flocksize), 
                       data = geese, family = "binomial", 
                       na.action = na.omit)


```

```{r examine_allmodels, eval = FALSE, warning=FALSE, message=FALSE}
#'summaries
summary(glmm_propjuv01); summary(glmm_propjuv02); summary(glmm_propjuv03)

#'Anova
Anova(glmm_propjuv01); Anova(glmm_propjuv02); Anova(glmm_propjuv03)

#'compare models
anova(glmm_propjuv02, glmm_propjuv03)
```

# Predictor significance, GLMM 2

```{r, echo=FALSE, warning=FALSE, message=FALSE} 
car::Anova(glmm_propjuv02)
```

# Predictor significance, GLMM 3

```{r, echo=FALSE, warning=FALSE, message=FALSE} 
car::Anova(glmm_propjuv03)
```

# Variance explained

```{r, eval=FALSE}
source("mixed_mods_rsquared.r")
o2m2 = o2.mixed.mods(glmm_propjuv02)
o2m3 = o2.mixed.mods(glmm_propjuv03)

o2glm1 = o2.mixed.mods(glm_propjuv01)
o2glm2 = o2.mixed.mods(glm_propjuv02)
```

- Using a metric, $\Omega^2$ similar to $R^2$
- Model 2 $\Omega^2$ : ```r o2m2```
- Model 3 $\Omega^2$ : ```r o2m3```
- Models do not explain much variance. Random effects not justified.


# Predictor significance, GLM 1

```{r, echo=FALSE, warning=FALSE, message=FALSE}
car::Anova(glm_propjuv01)
```

# Predictor significance, GLM 2

```{r, echo = FALSE,warning=FALSE, message=FALSE}
car::Anova(glm_propjuv02)
```

# Comparing linear models

```{r echo=FALSE, warning=FALSE, message=FALSE}
anova(glm_propjuv01, glm_propjuv02, test = "F")
```

- Model 1 $\Omega^2$: ```r o2glm1```

- Model 2 $\Omega^2$: ```r o2glm2```

```{r glm_propjuv01, eval=FALSE}
#'with interactions
glm_propjuv01 = glm(propjuv ~ Breeding_year*zone*winter_month, 
                     data = geese, family = "binomial")
```

```{r glm_propjuv02, eval= FALSE}
#'no interactions
glm_propjuv02 = glm(propjuv ~ Breeding_year+zone+winter_month, 
                     data = geese, family = "binomial")
```

```{r summaries_glms, eval=FALSE}
tidy(glm_propjuv01); tidy(glm_propjuv02)
```

```{r compare_models, eval=FALSE}
anova(glm_propjuv01, glm_propjuv02, test = "F")
```

```{r goodness_fit_glms, eval=FALSE}
o2.mixed.mods(glm_propjuv01); o2.mixed.mods(glm_propjuv02)
```

