Run family visits R script for revisit stats.

```{r load_data}
#load("famssplitMCMCmodel.rdata")
load("generated_data/split.mod.rdata")
```

# Predicting splits at the day level

event (split 1, other 0) ~ time in winter + flights (dist over 2km) per day + distance per day + total distance + family size

```{r load_daycoords}
load("generated_data/fsize_coords.rdata")

#'bind rows daycoords
daycoords = bind_rows(daycoords)
```

```{r}
library(move)
#'get speed, dist, lag, angle.
fam.move2 = lapply(fam.move, function(x){x = data.frame(speed = c(NA, speed(x)), dist = c(NA, distance(x)), angle = c(NA, angle(x)), lag = c(NA, timeLag(x)), lon = coordinates(x)[,1], lat = coordinates(x)[,2], time = timestamps(x))})

for(i in 1:13){
  fam.move2[[i]]$fam = names(fam.move2)[i]
}

#'now rbind
fam.move2 = bind_rows(fam.move2)

#'add splits
fam.move2 = merge(fam.move2,splits %>% dplyr::select(time, fam, event), by = c("time", "fam"), all.x = T)

fam.move2 = merge(fam.move2, daycoords[,c("fam","time","fsize")], by = c("fam","time"))

fam.move2 =  fam.move2 %>% arrange(fam, time)

fam.move2$event = ifelse(is.na(fam.move2$event), "other", fam.move2$event)

fam.move2$event = as.factor(fam.move2$event)
```


```{r}
#'get famsizes into event data
#fam.move2 = merge(fam.move2, daycoords[,c("fam","time","fsize")], by = c("fam","time"))

library(lubridate)
#'get time in winter
source("days_since.r")
fam.move2$days = days_since(fam.move2$time)
```

```{r prep_data}
#'remove outlier
#'get, per day, the mean and cumulative distances, the number of dists above 1km, mean time since winter, family size

#'distance over 1000m? split or not?
fam.move2$flight = fam.move2$dist > 1000
fam.move2$split = ifelse(fam.move2$event == "split", T, FALSE)

#'count flights
famstats =  data.frame(fam.move2 %>% group_by(fam, date = round_date(time, "day")) %>% summarise(mdist = mean(dist, na.rm = T), ddist = sum(na.omit(dist)), days = mean(days, na.rm = T), fsize = min(fsize), flights = sum(flight), split = sum(split), mlon = mean(lon, na.rm = T), mlat = mean(lat, na.rm = T)))


#'assign NA flight numbers to 0
famstats$flights[is.na(famstats$flights)] = 0

famstats = data.frame(famstats %>% group_by(fam) %>% mutate(tflights = c(cumsum((flights))), tdist = cumsum(ddist)))

#'make fam factor
famstats$fam = as.factor(famstats$fam)

#'set famstats splits value to 0 or 1. family An lost both juvs on one day. count all splits in the fam.
famstats = famstats %>% group_by(fam) %>% mutate(sumsplit = c(cumsum(split)))
famstats$split[famstats$split>0] = 1

#famstats = famstats %>% filter(fam %in% c("An","Ev","Ha","Jo","Ma","Na","Ro","Ti","Wo"))
```

```{r run_day_split_mod}
#'day split mod
library(mgcv)
library(lme4)
##library(MCMCglmm)
library(gamm4)
famstats = famstats[complete.cases(famstats),]

mod.day.split =
  glmer(split ~ fsize + flights + sqrt(ddist) + (1|fam), data = famstats, family = binomial(link = logit))

#modsplit2 =
 # bam(split ~ ti(flights)+ ti(log(ddist))+ ti(flights, log(ddist)) + ti(sqrt(days)) + ti(fsize) + ti(sqrt(days), fsize) + s(fam, bs = "re"), data = famstats, family = "binomial")

#famstats$predict = predict(mod.day.split, newdata = famstats, type = "response", allow.new.levels = T)
```

```{r summary_split_mod}
summary(mod.day.split)

#summary(modsplit2)

#'plot family size and days

save(mod.day.split, modsplit2, entry, file = "split.mod.rdata")

load("generated_data/split.mod.rdata")

m = predict(mod.day.split, newdata = famstats, type = "response", re.form =~(1|fam))
```



```{r merge_splitsmod_predicts}
#splitsmoddata$p = m

daycoords2 = daycoords %>% filter(lat < 54) %>% group_by(fam, time = round_date(time, "day")) %>% dmap(last)

famstats = merge(famstats, daycoords2, by.x = c("fam","date"), by.y = c("fam","time"))

famstats$fsize = famstats$fsize.x

famstats$p = predict(mod.day.split, newdata = famstats, type = "response", re.form =~(1|fam))

library(ggplot2)
a = theme(panel.grid = element_blank(), legend.position="none")

ggplot()+
  geom_path(data = famstats, aes(x = mlon, y = mlat, group = fam),
            col = ifelse(famstats$p >0.01, 2, 1))+
  facet_wrap(~fam, scales = "free")

```

## Fig 6a. p ~ size

```{r plot_day_split_probs}
#pdf(file = "~/git/thesis/texts/fig6a.pdf", height = 4, width = 4)
#'
f6a =
  ggplot()+
  #geom_vline(data = famstats %>% filter(split == 1), aes(xintercept=days), col = 2, lty = 3)+
  geom_boxplot(data = famstats, aes(x = juvs, y = p, group = juvs), fill = "grey90", width = 0.5)+
  labs(list(x = "Family size", y= "Daily split probability", title = "(a)"))+
  scale_y_continuous(labels = c(percent(seq(0,0.1, 0.025))))+
  theme_pub()+
  coord_cartesian(ylim=c(0,0.1))

#dev.off()
```

## Fig 6b. p ~ daily sum distance

```{r plot_flights_split}
#pdf(file = "~/git/family_sizes_geese_2018/texts/fig6d.pdf", height = 4, width = 4)
#'
f6b =
  ggplot()+
   #geom_vline(data = famstats %>% filter(split == 1), aes(xintercept=ddist/1e3), col = 2, lty = 1, lwd = 0.2)+
  #geom_line(data = visdistsplitdata, aes(x = ddist, y = visregFit), col = 1, lwd = 0.4)+
  geom_boxplot(data = famstats %>% mutate(x = cut(ddist/1e3, breaks = seq(0,100,10))) %>% 
                 filter(!is.na(x)), aes(x = x, y = p), fill = "grey90")+
  labs(list(x = "Distance travelled/day (km)", y= "Daily split probability", title = "(b)"))+
  theme_pub()+
  coord_cartesian(ylim = c(0,0.15))+
  scale_y_continuous(labels = c(percent(seq(0,0.15,0.05))))+
  scale_x_discrete(labels = c(seq(10, 80, 10), "90"))+
  theme(axis.text.x = element_text(size = 8))

#dev.off()
```


# Export png

```{r}
cairo_ps(filename = "figs/fig5.eps", width = 129/25.4, height = 84/25.4, pointsize = 8, family = "arial", fallback_resolution = 300)

gridExtra::grid.arrange(f6a, f6b, ncol = 2)

dev.off()
```
