---
title: Goose Flock Expanded Data
output: 
  tufte::tufte_handout
---

```{r, include=FALSE}
#'load knitr
library(knitr)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/")
```

```{r load data, include=FALSE}
#'load libs
library(readxl)
library(RColorBrewer)

#'import data
lt_geese = read_excel("~/git/thesis/Age-ratiodata-GWfG-toPratik.xlsx", 
    sheet = "Plain_table", col_types = c("text", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "numeric", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text"))
```

```{r reduce_data}
#'all records in the netherlands or nrw after than 2000

#'first keep only nl or nrw after 2000
study_site = lt_geese[lt_geese$Country == "NL"|lt_geese$Country=="NRW",]

#study_site = study_site[study_site$Breeding_year >= 2001,]
```


```{r assign_time}
#'fix missing days
study_site$Day = ifelse(is.na(study_site$Day),
                        15, study_site$Day)

#'use a time column of the posixct class
study_site$time = as.POSIXct(paste(study_site$Year,
                                   study_site$Month,study_site$Day),
                             format="%Y %m %d")
#'fix flock size
study_site$Total_flock = ifelse(is.na(study_site$Total_flock),
        ifelse(is.na(study_site$N_sampled),
               study_site$N_Adult+study_site$N_Juvenile,
               study_site$N_sampled),
                        study_site$Total_flock)

#'fix juvenile percentage
study_site$`Perc-JV` = ifelse(is.na(study_site$`Perc-JV`),
          study_site$N_Juvenile*100/study_site$Total_flock,
                        study_site$`Perc-JV`)

#'check for NAs
apply(study_site, 2, function(x){sum(is.na(x))})

#export to csv
study_site = study_site[study_site$time < "2012-05-01",]
write.csv(study_site, "clean_goose_data.csv")
```

To check how observations were clustered in space and time, I visualised the dates against the regions, as seen below. Averaging within dates is likely to mean averaging over regions at least in a few cases.


```{r create_limited_df, include=FALSE}
#'create limited data frame
goose_time = study_site[,c("Region","Breeding_year","Total_flock","Perc-JV","time")]

#'remove years above 2012
goose_time = goose_time[goose_time$time < "2012-05-01",]

summary(goose_time[is.na(goose_time$Region),])

#'complete cases for time
goose_time = goose_time[complete.cases(goose_time),]

#'where are the NAs?
apply(goose_time, 2, function(x){sum(is.na(x))})
```

```{r tilemap_space_time, fig.cap= "Sampling times in each region. Sampling is not even and is very sparse in some provinces.", fig.width=7, fig.height=3}
library(ggplot2)

ggplot(data = goose_time, 
       aes(x=Region, y=time))+ 
  geom_tile()+
  theme_bw()
```

```{r create_aggregate, warning=FALSE}
#'create a df aggregated as means with time as the factor
goose_aggregate = aggregate(goose_time,
                     list(goose_time$time), mean)

#'subset to remove factor date and region
goose_aggregate = goose_aggregate[,c(3:6)]

```


```{r creating_regularity}
#'create a daily sequence from the min to the max date
day_seq = seq(as.Date(min(goose_time$time)),
              as.Date(max(goose_time$time)), by = "day")

#should be more than 3600 days, since this is 10 years
length(day_seq)

#'now reduce to only y-m-d if not already so

#day_seq = as.POSIXct(day_seq, format = "%Y-%m-%d")
#'now merge goose_aggregate df with time seq

#'convert goose_aggregate$time to Date
#'oh dear, never thought i'd use as.Date!
goose_aggregate$time = as.Date(goose_aggregate$time)

#'merge the day sequence and the aggregated goose data
#'take care to keep empty places where there are no observations
goose_time_merge = merge(as.data.frame(day_seq), 
                         goose_aggregate, by.x = "day_seq", 
                         by.y = "time", all.x = T)

#'how many complete cases? same as the number of aggregated records
sum(complete.cases(goose_time_merge))

#'set all values where no records were taken to 0
#'not very realistic in the winter
goose_time_merge[is.na(goose_time_merge)] = 0

```



```{r plot_global_goose_trend, fig.width=3, warning=FALSE}
#'loess smoothing on flock size data
ggplot(data = goose_time_merge)+
  geom_path(aes(x = day_seq, y = Total_flock),
            col = "grey50")+
  stat_smooth(aes(x = day_seq, y = Total_flock),
              method = "loess", col = 1)+
  theme_bw()
```





