---
title: Importing Movebank family tracks
---

```{r set_env}
#'load knitr
library(knitr)
library(lubridate)
library(broom)
library(move)
library(RCurl)
library(bitops)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r login_search_studies}
#'store cred
cred <- movebankLogin(username="pratik", password="ccgFDRSFBS")

#'search studies
oldtags = searchMovebankStudies(x="LifeTrack Geese IG-RAS MPIO", login=cred)

newtags = searchMovebankStudies(x="Geese_MPIO_Kolguev2016", login=cred)
```

```{r get_2016_birds}
#'find animals
birds2016 = getMovebankAnimals(study=newtags, login=cred)

#'modify the animalName_deployment field to the actual animal name using sub. this is an important function.
birds2016$name = sub("(.*)_.*", "\\1", birds2016$animalName_deployment)
familynames2016 = birds2016$name[-c((grep("KOL", birds2016$name)),
                                     grep("RIET", birds2016$name))]

```

```{r get_2014_birds}
#'find animals
birds2014 = getMovebankAnimals(study = oldtags[2], login = cred)

#'get names
birds2014$name = sub("(.*)_.*", "\\1", birds2014$animalName_deployment)
familynames2014 = birds2014$name
```


```{r download_2016_tracks, eval=FALSE}
#'get all families
tracks2016 = getMovebankData(study=newtags,
                          animalName=familynames2016, login=cred)
```

```{r download_2014_tracks, eval=FALSE}

```

```{r remove spring records}
#'remove records after 1st april
tracks2016 = tracks2016[tracks2016$timestamp < "2017-04-01",]

#'save to file as rdata
save(tracks2016, file = "fams2016.rdata")

```


