---
title: Juvenile proportion ~ migration
---

```{r, include=FALSE}
#'load libs
library(knitr);library(lme4);library(lubridate);library(car);library(broom)
library(gamm4)
library(mgcv)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r read_goose_data, eval=FALSE}
geese = read.csv("data.goose.clean.csv",row.names = 1)
geese$time = as.Date(geese$time)
#'assign month
geese$month = month(geese$time)
#'make percentages proportions
geese$propjuv = geese$propjuv/100

#'assign wintermonth
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]

#'source days since
source("days_since.r")

geese$days = days_since(geese$time)

#'source omega squared
source("mixed_mods_rsquared.r")

#'remove zone Other
geese = geese[geese$zone != "Other",]
geese = droplevels(geese)
```

```{r read_migration_data}
migration = read.csv("migration_data.csv", row.names = 1)
migration$Date = as.Date(migration$Date)
```

```{r order_factors}
#'make zone an ordered factor
geese$zone1 = as.ordered(geese$zone)
#'set contrasts
contrasts(geese$zone1) = 'contr.treatment'
```

```{r merge data}
#'merge by date
a = merge(geese, migration, by.x = "time",by.y="Date", all.x=T)
```

```{r violin plot, fig.height=20}

library(ggplot2); library(dplyr)

migration %>% filter(activity %in% c("high")) %>%
ggplot()+
  geom_jitter(aes(x=activity, y = Date))+
  geom_violin(aes(x=activity, y = Date), alpha = 0.5, draw_quantiles = c(0.75))+
  facet_wrap(~Year+season, scales = "free")+ coord_flip()
```


```{r order_activity}
a$activity = as.ordered(a$activity)
contrasts(a$activity) = "contr.treatment"
```

```{r gam_migration, fig.height=10}

gam_mig01 = gam(propjuv ~ activity*zone1 +
                  s(timetopeak) +
                  s(timetopeak, by=activity)+
                  s(timetopeak, by=zone1),
                data = a, family = "binomial")

summary(gam_mig01)
AIC(gam_mig01)

o2.mixed.mods(gam_mig01)


```


