---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r set_env, message=FALSE, echo=FALSE, warning=FALSE}
#source libs
source("libs.R"); source("ggplot.pub.r")

#'load model libs
library(mgcv);library(gamm4)
#'load variogram libraries
library(sp);library(gstat)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE, eval=TRUE}
#dataprep
source("dataprep.R")
load("familysize_models.rdata");load("distmods.Rdata");load("mods_flocklevel.rdata")
```

# Fig 3. Distance to Kolguyev ~ family size

## get data
```{r get data fig2}
#'get data
#'dataset C
fams.expand = fams.expand %>% 
  mutate(distpred = predict(distmod, type = "response", allow.new.levels = T, newdata = fams.expand), data = "fams",
         stage = cut(t_since_in, breaks = c(0,90,180)))

#'dataset D
geeseorg = geeseorg %>% 
  mutate(distpred = predict(distmod2, type = "response", allow.new.levels = T, newdata = geeseorg), data = "geese.org",
         stage = cut(t_since_in, breaks = c(0,90,180)))

#'get the famsize, the timesincein, dataset name, and the prediction

fig2data = fams.expand %>% 
  dplyr::select(data, famsize, t_since_in, distpred, stage) %>% 
  rbind(geeseorg %>% select(data, famsize, t_since_in, distpred, stage)) %>% 
  filter(t_since_in <= 200) %>%  
  group_by(data, famsize, stage) %>% 
  summarise(mean = mean(distpred,na.rm=T), 
            sd = sd(distpred, na.rm = T), 
            n = length(distpred)) %>% 
  mutate(ci = qnorm(0.975)*sd/sqrt(n))

fig2data2 = fams.expand %>% 
  dplyr::select(data, famsize, t_since_in, distpred, stage, mintemp) %>% 
  rbind(geeseorg %>% select(data, famsize, t_since_in, distpred, stage, mintemp)) %>% 
  filter(t_since_in <= 200) %>%  
  mutate(tempround = round_any(mintemp, 5)) %>% 
  group_by(data, tempround) %>% 
  summarise(mean = mean(distpred,na.rm=T), 
            sd = sd(distpred, na.rm = T), 
            n = length(distpred)) %>% 
  mutate(ci = qnorm(0.975)*sd/sqrt(n))
```


## plot fig 3

```{r export_distkol_fams1, eval = FALSE}
cairo_pdf(filename = "figs/fig3.pdf", height = 85/25.4, width = 180/25.4)

#'plot

fig2data %>% 
 
ggplot()+
  geom_smooth(aes(x = famsize, y = mean, lty = stage, group = stage), se = F, col = 1, lwd = 0.5)+
  
  geom_pointrange(aes(x = famsize, y = mean, ymin = mean-ci, ymax = mean+ci, shape = stage, fill = stage), position = position_dodge(width = 0.2))+
  
  facet_wrap(~ifelse(data == "fams", "(a)", "(b)"), scales = "free")+
  labs(list(x = "Family size", y = "Distance to breeding grounds (km)"))+
  theme_pub()+
  theme(strip.text = element_text(face = "bold", hjust = 0, size = 12))+
  scale_shape_manual(values = c(21,22))+
  xlim(-0.1,7.5)+
  scale_fill_manual(values = c("white","grey", "black"))+
  scale_y_continuous(breaks = c(2850,2900,2950))+
  coord_cartesian(ylim = c(2850,2950))
  
dev.off()
```

# Fig 4. Family siz

## Fig 4a. Obs data

## get data
```{r}
#'use fambirds and geese
pfam.pred = predict(famprop.mod, type = "response", allow.new.levels = T, newdata = fambirds)
pfamjuvs.pred = predict(famjuvprop.mod, type = "response", allow.new.levels = T, newdata = fambirds)

#'get predicted values
fig5data1 = fambirds %>% mutate(pfam.pred, pfamjuvs.pred) %>% select(t_since_in, pfam.pred, pfamjuvs.pred) %>% mutate(days = round_any(t_since_in, 10)) %>% select(-t_since_in) %>% melt(id.vars = "days") %>% group_by(days, variable) %>% summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T), n = length(value)) %>% mutate(ci = qnorm(0.975)*sd/sqrt(n))
```

```{r model_preds_mod03}
#'get model responses
#'dataset B
fams.expand = fams.expand %>% 
  mutate(fsizepred = predict(mod.famsize.flock.time, type = "response", allow.new.levels = T, newdata = fams.expand), data = "fams")

#'dataset C
geeseorg = geeseorg %>% 
  mutate(fsizepred = predict(mod.famsize.geeseorg, type = "response", allow.new.levels = T, newdata = geeseorg), data = "geeseorg")

#'get plot data
fig3data = fams.expand %>% 
  dplyr::select(data, t_since_in, fsizepred) %>% 
  rbind(geeseorg %>% select(data,t_since_in, fsizepred)) %>% 
  filter(t_since_in <= 200) %>% 
  group_by(data, days = round_any(t_since_in, 10)) %>% 
  summarise(mean = mean(fsizepred,na.rm=T), sd = sd(fsizepred), n = length(fsizepred)) %>%
  mutate(ci = qnorm(0.975)*sd/sqrt(n))

#'get summary data
fig3data2 = fams.expand %>% 
  dplyr::select(data, t_since_in, flocksize, fsizepred) %>% 
 # rbind(geeseorg %>% select(data,t_since_in, fsizepred)) %>% 
  filter(t_since_in <=200, flocksize < 5000) %>% 
  group_by(data, flocksize = cut(flocksize, breaks = seq(0,4000, 100))) %>% 
  summarise(mean = mean(fsizepred,na.rm=T), sd = sd(fsizepred), n = length(fsizepred)) %>%
  mutate(ci = qnorm(0.975)*sd/sqrt(n))
```

```{r export_fam_time}
fig4a=
fig3data %>%  
ggplot()+
  geom_smooth(data = fig3data, aes(x = days, y = mean, lty = data), lwd = 0.5, col = 1, method = "glm", fill = "grey80")+
  
  geom_pointrange(data = fig3data, aes(x = days, y = mean, ymin = mean - ci, ymax = mean + ci, shape = data), fill = "white", position = position_dodge(width = 5))+
  
  geom_smooth(data = fig5data1 %>% filter(variable == "pfamjuvs.pred"), aes(x = days, y = (1 - mean)*4), col = 1, lty = 2, method = "glm", lwd = 0.5, fill = "grey80")+
  
  geom_pointrange(data = fig5data1 %>% filter(variable == "pfamjuvs.pred"), aes(x = days, y = (1 - mean)*4, ymin = (1 - mean-ci)*4, ymax = (1-mean+ci)*4), shape = 24, fill = "white")+
  
  scale_y_continuous(sec.axis = sec_axis(~.*0.5, name = "Proportion indepent juveniles", labels = percent(seq(0,1,0.25))))+
  
  scale_shape_manual(values=c(21,22))+
  scale_fill_manual(values = c("black", "grey"))+
  labs(list(x = "Days since arrival", y = "Family size", title = "(a)"))+
  xlim(0,180)+
  theme_pub()

```

## Fig 4b. GPS data

```{r get_data}
load("generated_data/splits.with.ids.rdata")
```


```{r plot_3b}
#pdf(file = "~/git/thesis/texts/fig3b.pdf", height = 4, width = 4)

splits = splits[!duplicated(splits[,c("fam","juvs","event")]),]
#'family Ev lost a juvenile on the last day recorded in the study period/area
splits["13",8] = "split"

# %>% #filter(fam %in% c("Ev","Wo","Ha","Na","Ti","Ma","Ro","An","Jo"))
         

data = splits %>% filter(fam %in% c("Ev","Wo","Ha","Na","Ti","Ma","Ro","An","Jo"))

fig4b = 
ggplot(data)+
  geom_line(aes(x = t_since_in, y= juvs, group = fam), lty = 1, lwd = 0.4)+
  geom_point(aes(x = t_since_in, y = juvs), shape = 21, fill = "white")+
  
  scale_shape_manual(values = c(as.character(unique(data$fam))))+
  
  theme_pub()+
  scale_y_continuous(breaks= c(0,3,5))+
  labs(list(x = "Days since arrival", y = "Family size", title = "(b)", shape = "Family", colour = "Family"))+
  facet_wrap(~fam, scales = "fixed", switch = "x")+
  coord_cartesian(ylim=c(0,5), xlim = c(30, 180))+
  theme(legend.position = "none", legend.direction = "vertical",legend.key = element_blank(), strip.background = element_rect(fill = "transparent", colour = "transparent"), strip.text = element_text(face = "bold", size = 8), plot.background = element_blank())

#dev.off()
```

## Export fig 4

```{r export fig3}
#'export to ps
cairo_pdf(filename = "figs/fig4.pdf", height = 100/25.4, width = 180/25.4)

#fig3a
library(gridExtra)

gridExtra::grid.arrange(fig4a, fig4b, ncol = 2)

dev.off()
```

# Fig 7. Split probability

see goosecode034

# Fig 5. Independent juveniles

## get data
```{r}
#'use fambirds and geese
pfam.pred = predict(famprop.mod, type = "response", allow.new.levels = T, newdata = fambirds)
pfamjuvs.pred = predict(famjuvprop.mod, type = "response", allow.new.levels = T, newdata = fambirds)

#'get predicted values
fig5data1 = fambirds %>% mutate(pfam.pred, pfamjuvs.pred) %>% select(t_since_in, pfam.pred, pfamjuvs.pred) %>% mutate(days = round_any(t_since_in, 10)) %>% select(-t_since_in) %>% melt(id.vars = "days") %>% group_by(days, variable) %>% summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T), n = length(value)) %>% mutate(ci = qnorm(0.975)*sd/sqrt(n))
```

## plot data

```{r}
fig5data1 %>% filter(variable == "pfamjuvs.pred") %>% 
  ggplot()+
  geom_smooth(aes(x = days, y = (1 - mean), group = variable), col = 1, method = "glm", lwd = 0.5)+
  geom_pointrange(aes(x = days, y = (1 - mean), ymin = (1 - mean-ci), ymax = (1-mean+ci)), lwd = 0.2, fatten = 10)+
 # facet_wrap(~variable, scales = "free")+
  theme_pub()
```

# Fig 6: Flock level patterns

## get data
```{r}
#'family proportion over time, juvenile proportion in flocks, independent juveniles in flocks

#'get data on the famprop and independent juveniles in flocksize
fig5data2 = fambirds %>% 
  mutate(pfam.pred, a = 1-pfamjuvs.pred) %>% 
  select(flocksize, pfam.pred, a) %>% 
  mutate(flocksize = round_any(flocksize, 100)) %>% 
  melt(id.vars = "flocksize") %>% 
  group_by(flocksize, variable) %>% 
  summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T), n = length(value)) %>% 
  mutate(ci = qnorm(0.975)*sd/sqrt(n))

fig6data = geese %>% 
  mutate(pjuv = predict(juvprop.mod, newdata = geese, allow.new.levels = T, type = "response")) %>% 
  select(flocksize, pjuv) %>% 
  mutate(flocksize = round_any(flocksize, 100)) %>% 
  melt(id.vars = "flocksize") %>% 
  group_by(flocksize, variable) %>% 
  summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T), n = length(value)) %>% mutate(ci = qnorm(0.975)*sd/sqrt(n))

fig5cdata = geese %>% 
  mutate(pjuv = predict(juvprop.mod, newdata = geese, allow.new.levels = T, type = "response")) %>% 
  select(t_since_in, pjuv, propjuv) %>% 
  mutate(t_since_in = round_any(t_since_in, 10)) %>% 
  melt(id.vars = "t_since_in") %>% 
  group_by(t_since_in, variable) %>% 
  summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T), n = length(value)) %>% mutate(ci = qnorm(0.975)*sd/sqrt(n))
```

## make 3 panel plot

```{r}
#'get fig6a
fig6b = 
  ggplot()+
  geom_smooth(data = fig5data1 %>% filter(variable == "pfam.pred"), aes(x = days, y = mean), se =T, method = "glm", col = 1, lwd = 0.5, fill = "grey80")+
  geom_pointrange(data = fig5data1 %>% filter(variable == "pfam.pred"), aes(x = days, y = mean, ymin = mean-ci, ymax = mean+ci), fill = "white", shape = 21)+
  scale_y_continuous(breaks = c(0,0.2,0.4), labels = c(percent(c(0,.2,.4))))+
  
  facet_wrap(~variable)+
  theme_pub()+
  theme(strip.text = element_blank())+
  labs(list(x = "Days since arrival", y = "Family proportion of flock", title = "(b)"))
```

```{r}
#'get other figs
fig6a = 
  ggplot(fig5data2 %>% filter(variable == "pfam.pred"))+
  geom_ribbon(aes(x = flocksize, y = mean, ymin = mean -ci, ymax = mean+ci, group = variable), fill = "grey80", lwd = 0.5)+
  geom_line(aes(x = flocksize, y = mean, ymin = mean -ci, ymax = mean+ci, group = variable), lwd = 0.5)+
  
  geom_pointrange(aes(x = flocksize, y = mean, ymin = mean-ci, ymax = mean+ci), shape = 21, fill = "white")+
    ylim(0,NA)+
  scale_y_continuous(breaks = c(0,.25,0.5), labels = c(percent(c(0,.25,.5))))+
  coord_cartesian(xlim = c(0,2500))+

  labs(list(x = "Flock size", y = "Family proportion of flock", title = "(a)"))+
  theme_pub()+theme(strip.text = element_text(face = "bold", hjust = 0))
```

```{r}
fig6d = 
  ggplot()+
  geom_smooth(data = fig5cdata %>% filter(variable == "pjuv"), aes(x = t_since_in, y = mean), fill = "grey80", lwd = 0.5, col = 1, method = "glm")+
  #geom_line(aes(x = flocksize, y = mean, ymin = mean -ci, ymax = mean+ci, group = variable), lwd = 0.5)+
  
  geom_pointrange(data = fig5cdata %>% filter(variable == "propjuv"), aes(x = t_since_in, y = mean, ymin = mean-ci, ymax = mean+ci), shape = 21, fill = "white")+
  
  scale_y_continuous(breaks = seq(0.15,0.35,0.1), labels = c(percent(seq(0.15,0.35,0.1))))+
  coord_cartesian(xlim = c(0,180), ylim = c(0.125,0.35))+
  labs(list(x = "Days since arrival", y = "Proportion of juveniles", title = "(d)"))+
  theme_pub()+theme(strip.text = element_text(face = "bold", hjust = 0))

  ###########################
  
fig6c = 
  ggplot(fig5data2 %>% filter(variable == "a"))+
  geom_smooth(aes(x = flocksize, y = mean, ymin = mean -ci, ymax = mean+ci, group = variable), fill = "grey80", lwd = 0.5, col = 1, method = "loess")+
  #geom_line(aes(x = flocksize, y = mean, ymin = mean -ci, ymax = mean+ci, group = variable), lwd = 0.5)+
  
  geom_pointrange(aes(x = flocksize, y = mean, ymin = mean-ci, ymax = mean+ci), shape = 21, fill = "white")+
  
  #facet_wrap(~ifelse(variable == "pfam.pred", "(b)", "(c)"), scales = "free")+
  coord_cartesian(xlim = c(0,2100), ylim = c(0,0.5))+
  scale_y_continuous(breaks = seq(0,0.5,0.25), labels = c(percent(c(seq(0,0.5,0.25)))))+
  labs(list(x = "Flock size", y = "Proportion indpendent juveniles", title = "(c)"))+
  theme_pub()+theme(strip.text = element_text(face = "bold", hjust = 0))
```

## export fig 6

```{r}
#'export to eps
cairo_pdf(filename = "figs/fig6.pdf", height = 180/25.4, width = 180/25.4)

library(gridExtra)

gridExtra::grid.arrange(fig6a, fig6b, fig6c, fig6d, nrow = 2)

dev.off()
```

