---
title: Geocoding 02
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(lubridate)
library(dplyr)
library(readxl)

#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r import_sites}
#'import sites from new data
sites = read_excel("~/git/thesis/Age-ratiodata-GWfG-toPratik.xlsx", sheet = 5)

#'get unique site names
geocode.sites =  sites %>% filter(Country %in% c("NL","NRW")) %>% group_by(Site_name) %>% summarise(country = first(Country), region = first(Region), site = first(Site_name), lookup = first(Lookup_site))
```

```{r get_sites}
#'geocode unique lookup names
library(ggmap)
#'unique lookups
#lookups = as.character(na.omit(unique(geocode.sites$lookup)))
#'get coords
#site.coords = geocode(lookups)
```

```{r merge_data}
#'bind
site.coords.names = cbind(site.coords, lookups)

#'merge with sites and lookup info
geocode.sites = merge(geocode.sites, site.coords.names, by.x = "lookup",
                      by.y = "lookups", all.x = T)

#' how many sites without coords?
apply(geocode.sites, 2, function(x) sum(is.na(x)))

#'where are the NAs?
geocode.sites %>% filter(is.na(lookup))
```

```{r export_sites}
#'export sites to csv
write.csv(geocode.sites, "geocode.sites.csv")
```

```{r make_spatial}
library(sp)
#'remove incomplete cases. around 30 sites are removed
map.sites = geocode.sites[complete.cases(geocode.sites),]
#'make spatial
coordinates(map.sites) = ~lon+lat
```

```{r map_sites}
library(tmap)
library(rgdal);library(raster)
#ĺoad nl
library(ggplot2)
coast = readOGR("vector/ne_10m_land.shp")
nl = readOGR("vector/ne_10m_admin_0_boundary_lines_land.shp")

#'remove sites outside 0-10, 53-56
e = extent(map.sites)

e[1] = 4;e[2] = 10;e[3] = 50

#mmap sites
tm_shape(nl, bbox = e+0.5)+
  tm_lines()+
tm_shape(coast)+
  tm_polygons(col = "grey80",alpha = 0.1)+
tm_shape(map.sites)+
  tm_symbols()+
tm_scale_bar(position = c("left","bottom"), breaks=c(0,100,200))+
  tm_format_NLD()+
  tm_layout(frame = T, title = "Geocoded sites")

```

