---
title: Family size models
bibliography: ~/git/thesis/geese_citations.bib
fontsize: 8pt
link-citations: true
citecolor: Emerald
output: 
  pdf_document: 
    keep_tex: yes
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(ggplot2)
library(lme4)
library(lubridate)
library(car)
library(mgcv)
library(gamm4)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r import_data, include = FALSE}
#'load geese, fams and fams expanded
geese = read.csv("data.goose.clean.csv", row.names = 1)
fams = read.csv("fams.csv", row.names = 1)
fams.expand = read.csv("fams.expand.coords.csv")

#'convery perc to prop
geese$propjuv = round(geese$propjuv/100, 4)

#'drop zone Other
geese = geese[geese$zone != "Other",]

#'juvenile proportion is actually N_juv/N_sampled
#plot(geese$propjuv2 ~ geese$propjuv,
  #   main = "Calculated vs provided juv prop.",
  #   xlab = "Provided in data",
  #   ylab = "Calculated as N_juvs/No. of whitefronts")

#'change class of time variable to Date
geese$time = as.Date(geese$time)
fams$time = as.Date(fams$time)
fams.expand$time = as.Date(fams.expand$time)

#'add month and day
geese$month = month(geese$time)
geese$day = day(geese$time)

#'assign  random coords for gams
geese$rand.lon = rnorm(length(geese$lon), geese$lon, 0.1)
geese$rand.lat = rnorm(length(geese$lat), geese$lat, 0.1)
```

```{r winter_month}
#'classify months based on their order in the winter
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]

#'also for fams.expand
#'first assign month
fams.expand$month = month(fams.expand$time)
#'now wintermonth
fams.expand$winter_month =  c(c(1:8), fams.expand$month)[match(fams.expand$month, c(c(9:12,1:4), fams.expand$month))]
```

# Mean family size as response

## Linear model

```{r glm_global}
glm_famsize01 = glm(meanfam ~ Breeding_year*winter_month*zone, family = "poisson", data = geese, na.action = na.omit)

#'summary
summary(glm_famsize01)

#'plot
plot(glm_famsize01)

#'look for significance of predictors
Anova(glm_famsize01)

#'winter month is a significant pedictors of mean family size, but the model doesn't explain more than 10% of the variance in the data
```

```{r glm_global}
#'use fams.coords
glm_famsize02 = glm(famsize ~ Breeding_year*winter_month*zone, family = "poisson", data = fams.expand, na.action = na.omit)

summary(glm_famsize02)

plot(glm_famsize02)
```

```{r gam_meanfam}
gam_meanfam01 = gam(meanfam ~ ti(Breeding_year) + ti(Breeding_year, winter_month), data = fams.expand, family = "poisson")

summary(gam_meanfam01)

plot(gam_meanfam01, residuals = T)

vis.gam(gam_meanfam01, 
        theta = 10, phi = 25, 
        plot.type = "persp", 
        ticktype = "detailed", 
        type = "response", 
        zlab = "mean fam size",
        color = "terrain")
```

```{r gam_meanfam_global}

gam_meanfam_global01 = gamm(meanfam ~ ti(Breeding_year) + ti(winter_month) + ti(Breeding_year, winter_month) + s(lon, lat) + te(Breeding_year,winter_month,lon,lat), random = list(Observer=~1, Food_type=~1, flocksize=~1), data = fams.expand, family = "poisson")

```

