---
title: Family size of tracked birds
---

```{r load_env}
source("knitr_options.r")
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r load_famtracks}
#'list fam data files
famfiles = list.files("NoBoutFamilies/", pattern = ".kml", full.names = T)

#'each individual is a layer in the kml file. create a list of vectors, each vector containing the names of the layers/birds in that layer.
famlayers = list()
for(i in 1:length(famfiles)){
famlayers[[i]] = ogrListLayers(famfiles[i])
}

#'read in each layer of each kml file
f = readOGR("NoBoutFamilies/NoBout_Adfamily.kml", layer = "43_AdrieII_M", require_geomType = "wkbPoint")

library(maptools)
#'create a list of named lists
famtracks = list(ad = list(), an = list(), ja = list(),
                 ev = list(), ha = list(), he = list(),
                 ch = list(), jo = list(), ma = list(),
                 na = list(), ro = list(), ti = list(),
                 wo = list())

#'fill this named list with point objects from the kml files of each goose, with families forming a single spdf in each list.
for(i in 1:length(famfiles)){
  for(j in 1:length(famlayers[[i]]))
  famtracks[[i]][[j]] = readOGR(famfiles[i], layer = famlayers[[i]][j], require_geomType = "wkbPoint")
}
```

```{r remove_spring_dates}

#'get all times as date objects
famtracktimes = lapply(famtracks, function(x){
  lapply(x, function(y){
    as.Date(y$Name)})
  })

#'combine lists
for(i in 1:length(famtracks)){
  for(j in 1:length(famtracks[[i]]))
  famtracks[[i]][[j]]$time = famtracktimes[[i]][[j]]
}
```

