---
title: "Juvenile proportions GAM by zone"
output:
  beamer_presentation: 
    colortheme: seagull
    fonttheme: structurebold
    theme: Luebeck
fontsize: 8pt
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(lme4)
library(lubridate)
library(car)
library(broom)
library(gamm4)
library(mgcv)
library(itsadug)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")

load("goose_code_015gamsbyzone.RData")
```

```{r read_data, eval=FALSE}
geese = read.csv("data.goose.clean.csv",row.names = 1)
geese$time = as.Date(geese$time)
#'assign month
geese$month = month(geese$time)
#'make percentages proportions
geese$propjuv = geese$propjuv/100

#'assign wintermonth
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]

#'source days since
source("days_since.r")

geese$days = days_since(geese$time)

#'source omega squared
source("mixed_mods_rsquared.r")

#'remove zone Other
geese = geese[geese$zone != "Other",]
geese = droplevels(geese)
```

```{r gam01, eval=FALSE}
#'global gam without mixed effects
gam01 = gam(propjuv ~ s(Breeding_year, by = zone) +
              s(days, by = zone) +
              ti(Breeding_year, days, by = zone), 
            data = geese, family = "binomial")
```

```{r vis_gam01, eval=FALSE}
par(mfrow = c(1,2))
vis.gam(gam01, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone","Breeding_year"),
        n.grid = 20, ticktype = "detailed")

vis.gam(gam01, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone","days"),
        n.grid = 20, ticktype = "detailed")
par(mfrow = c(1,1))
```

```{r summary_gam01, eval=FALSE}
summary(gam01)
```

```{r order_zone, eval=FALSE}
#'make ordered factor
geese$zone1 = as.ordered(geese$zone)
#'set contrasts
contrasts(geese$zone1) = 'contr.treatment'
```

```{r gam02_ordered_facs, eval=FALSE}
#'global gam without mixed effects, but added reference smooth
gam02 = gam(propjuv ~ s(Breeding_year) + s(Breeding_year, by = zone1) +
              s(days) + s(days, by = zone1), 
            data = geese, family = "binomial")
```

```{r summary_gam02, eval=FALSE}
summary(gam02)
```

# Effects of year

```{r plot_gam02, echo=FALSE, fig.cap="Lemming cycle effect appears dampened in more recent years."}
plot.gam(gam02, select = 1, shade = T,
         rug =T, residuals = T,
        main = "juvenile proportion")
```

```{r vis_gam02, eval=FALSE}
par(mfrow = c(1,2))
vis.gam(gam02, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone1","Breeding_year"),
        n.grid = 20, ticktype = "detailed")

vis.gam(gam02, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone1","days"),
        n.grid = 20, ticktype = "detailed")

par(mfrow = c(1,1))
```

# With random effects

```{r gamm01, eval=FALSE}
#'global gam without mixed effects, but added reference smooth
gamm01 = gam(propjuv ~ s(Breeding_year) + s(Breeding_year, by = zone1) + s(Food_type, Breeding_year, bs="re") + s(Observer, Breeding_year, bs = "re") + s(flocksize, Breeding_year, bs = "re"),
            data = geese, family = "binomial")
```

```{r summary_gamm01, eval=FALSE}
summary(gamm01)
```

```{r gamm02, eval=FALSE}
#'global gamm including days
gamm02 = gam(propjuv ~ s(Breeding_year) + s(Breeding_year, by = zone1) +
               +s(days) +s(days, by=zone1) + s(Food_type, Breeding_year, bs="re") + s(Observer, Breeding_year, bs = "re") + s(flocksize, Breeding_year, bs = "re"),
            data = geese, family = "binomial")
```

```{r summary_gamm02}
summary(gamm02)
```

- Breeding year is the only significant predictor
- Days in winter is not significant.

# Effect of year and days by zone
```{r vis_gamm02, fig.height=8, fig.width=12}
par(mfrow = c(1,2))
vis.gam(gamm02, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone1","Breeding_year"),
        n.grid = 20, ticktype = "detailed")

vis.gam(gamm02, type = "response", theta = 50, phi = 45,
        color = "cm", plot.type = "persp",
        main = "juvenile proportion", view = c("zone1","days"),
        n.grid = 20, ticktype = "detailed")

par(mfrow = c(1,1))
```

# Including mixed effects

- Including mixed effects reduces AIC significantly.
- AIC (GAM without mixed effects): ```r AIC(gam02)```
- AIC (GAM with mixed effects): ```r AIC(gamm02)```
