---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r load_env, message=FALSE, warning=FALSE}
source("knitr_options.r")
library(zoo);library(plyr);library(dplyr);library(purrr);library(purrrlyr)
#'suppress all code output but run code
opts_chunk$set(eval = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r load_famtracks}
load("fams2016.nobursts.rdata")
load("fams2014.rdata")
load("fams2015.rdata")
```


```{r join_lists}
#'modify lists to have the reference adult in position 1
#'fam An
fams2014[["An"]] = rev(fams2014[["An"]])
#'fam Ro
fams2014[["Ro"]] = fams2014[["Ro"]][c(2,3,1,4)]

#'family Ha
fams2015[["Ha"]] = fams2015[["Ha"]][c(3,1,2,4,5)]

#'family Jo
fams2015[["Jo"]] = rev(fams2015[["Jo"]])

#'family Na
fams2015[["Na"]] = fams2015[["Na"]][c(2,3,1,4,5)]

#'family Ad
fams2016.4[["Ad"]] = fams2016.4[["Ad"]][c(3,2,1,4,5)]

#'family Ti
fams2016.4[["Ti"]] = fams2016.4[["Ti"]][c(3,2,1,4)]

#'family Ev
fams2016.4[["Ev"]] = fams2016.4[["Ev"]][c(5,4,1,2,3,6)]

#'family Wo
fams2016.4[["Wo"]] = fams2016.4[["Wo"]][c(4,3,1,2,5)]
```

```{r}
#'remove dates outside the single year
fams2014 = lapply(fams2014, function(x){lapply(x, function(y){y %>% filter(t < "2014-05-01")})})

fams2015 = lapply(fams2015, function(x){lapply(x, function(y){y %>% filter(t < "2015-05-01")})})
```


```{r append_lists}
#'merge lists
f1 = append(fams2014, c(fams2015, fams2016.4))
```


```{r add_names_tracks}
#add bird names to tracks and assign age
for(i in 1:13){
    for(j in 1:length(f1[[i]])){
        f1[[i]][[j]]$id = names(f1[[i]])[j]
        f1[[i]][[j]]$age = ifelse(f1[[i]][[j]]$id %in% c("X43_AdrieII_M","X44_Adriana_F","Anna","Anton","X71_Jan_M","X70_Janika_F", "X52_EvertII_M","X53_Eva_F", "Hannah","HArkady","HeBerend","Hennie","X82_Chris_M", "X81_Christa_F", "Jouri","Jolanda","Mari","Maria","Nanneke","Napoleon","Rolf","Ronja","X48_Tineke_F","X49_Timo_M", "X58_WouterII_M", "X59_Wolka_F"), "ad", "juv")
    }
}
```


```{r round_time}
f1 = lapply(f1, function(x){lapply(x, function(y){y %>% mutate(t = round_date(t, "30 minute"))})})


#'remove v, fam, and lag
f1 = lapply(f1, function(x){lapply(x, function(y){y %>% dplyr::select(t, lon, lat)})})

library(data.table)
#'round position to the half hour
f1 = lapply(f1, function(x){lapply(x, function(y){y %>% group_by(t) %>% summarise(lon = mean(lon, na.rm = T), lat = mean(lat, na.rm = T), id = unique(id), age = unique(age))})})
```

```{r distances}
library(purrr); library(purrrlyr)
#'a left join here
f2 = lapply(f1, function(x){reduce(x, left_join, by = "t")})
```

```{r get_distances}
library(geosphere)

#'get distances in another list

fdists = vector("list", 13)

for(z in 1:length(f2)){
 for(i in 1:dim(f2[[z]])[1]){
  for(j in seq(1, length(f2[[z]])-2 ,2))
   fdists[[z]] = c(fdists[[z]], distVincentyEllipsoid(p1 = f2[[z]][i,c(2,3)], p2 = f2[[z]][i,c(j+1,j+2)]))
}
}
```

```{r dist_matrix}
#'make a duplicate
fdistm = fdists

#'make each numeric column a matrix. this will need a for loop
for(i in 1:length(f2)){
  fdistm[[i]] = matrix(fdistm[[i]], ncol = length(f1[[i]]), byrow = T)
}
```

```{r convert_to_df}
#'make dists a df
fdistm = lapply(fdistm, function(x){x = as.data.frame(x)})

#'add names to dfs
names(fdistm) = names(f2)

#'add column names
for(i in 1:13){
  colnames(fdistm[[i]]) = names(f1[[i]])
}
```

```{r}
save(fdistm, f2, file = "famdists02.rdata")

load("famdists02.rdata")
```

```{r}
#'set all NA to Inf. turns the dfs into a list again.
#fdistm2 = lapply(fdistm, function(x){lapply(x, function(y){replace(y, which(is.na(y)), NA)})})
fdistm2 = fdistm

#'are indivs within 1km or not?
fdistm2 = lapply(fdistm, function(x) x < 1000)

for(i in 1:13) fdistm2[[i]][is.na(fdistm2[[i]])] = 0

for(i in 1:13) fdistm2[[i]] = rollapply(fdistm2[[i]], seq(dim(fdistm2[[i]])[1],1), max, align = "left")

#fdistm2 = lapply(fdistm2, function(x) x = as.data.frame(x))

#'assign age
for(i in 1:13) colnames(fdistm2[[i]]) = ifelse(colnames(fdistm2[[i]]) %in% c("X43_AdrieII_M","X44_Adriana_F","Anna","Anton","X71_Jan_M","X70_Janika_F", "X52_EvertII_M","X53_Eva_F", "Hannah","HArkady","HeBerend","Hennie","X82_Chris_M", "X81_Christa_F", "Jouri","Jolanda","Mari","Maria","Nanneke","Napoleon","Rolf","Ronja","X48_Tineke_F","X49_Timo_M", "X58_WouterII_M", "X59_Wolka_F"), "ad", "juv")

#'count juvs and ads in each fam

for (i in 1:13) {
  b = fdistm2[[i]]
  fdistm2[[i]] = cbind(b, juvs = apply(b[,colnames(b) == "juv"], 1, sum), ads = apply(b[,colnames(b) == "ad"], 1, sum))
}

#'get family sizes per half hour
fdistm3 = list()
fdistm3 = lapply(fdistm, function(x){x = x %>% mutate(fsize= apply(x, 1, function(y){sum(y < 1e3, na.rm = T)}))})

for(i in 1:13) fdistm3[[i]]$fsize = rollapply(fdistm3[[i]]$fsize, seq(dim(fdistm[[i]])[1],1), function(x) max(x, na.rm = T), align = "left")
```


```{r add_time}
#'add the timestamps to the matrix
for(i in 1:length(f2)){
  fdistm2[[i]] = cbind(fdistm2[[i]], time = (f2[[i]]$t))
  fdistm3[[i]] = cbind(fdistm3[[i]], time = (f2[[i]]$t))
}

library(lubridate)

#'round time to the day
#fdistm3 = lapply(fdistm3, function(x){x = x %>% mutate(time = round_date(time, "day"), fsize)})

#'17/12/17 work. find which geese are present in 1km on each day
#fdistm2 = lapply(fdistm2, function(x){x = x %>% group_by(time = round_date(time, "day")) %>% dmap(max)})
```

```{r get_maxsize}
library(purrr);library(zoo)
#'get max family size per day
#fsize2 = lapply(fsize, function(x){x = x %>% slice_rows("time") %>% dmap(max)})

#'set famsize to the max famsize in the next n fixes
#fsize2 = lapply(fdistm3, function(x){x = x %>% mutate(fsize = rollapply(fsize, seq(dim(x)[1],1), max, align = "left"))})
```

```{r save_fam_size_data}
save(fsize2, file = "fsize.rdata")

load("fsize.rdata")
```


```{r get_coords}
#'get coords
daycoords = lapply(f2, function(x){x %>% select(t, lon.x, lat.x) %>% plyr::summarise(time = round_date(t, "30 minute"), lon = lon.x, lat = lat.x) %>% slice_rows("time") %>% dmap(mean)})

#'merge coords with fsize2 and assign families
for(i in 1:length(daycoords)){
  daycoords[[i]] = cbind(daycoords[[i]], fsize = fdistm3[[i]]$fsize, fdistm2[[i]][,c("ads","juvs")])
  daycoords[[i]]$fam = names(fdistm3)[i]
}

#'keep rel cols
famcoords = lapply(daycoords, function(x){x %>% select(time, lon, lat, fam)})
#'rbind the list
famcoords = bind_rows(daycoords)

save(daycoords, file = "fsize_coords.rdata")

```


```{r find_splits}
#'select rel cols
daycoords = bind_rows(daycoords)
#'split by family
splits = dlply(daycoords, "fam")

#'get attrs at split
splits2 = lapply(splits, function(x){x[which(diff(x$fsize)<0)+1,]})

#'get the start and end points of the tracks.
ends = lapply(splits, function(x){rbind(x[1,], x[dim(x)[1],])})

#'combine split data. 17/12/17, splits3 subbed for splits2
#splits2 = bind_rows(splits3)
#splits2$event = "Split"

splits2 = splits2 %>% map(function(x) x %>% mutate(event = "split"))

ends = ends %>% map(function(x) x %>% mutate(event = c("start","end")))

#'attach ends to fam splits within lists, ie, splits3
for (i in 1:13) splits2[[i]] = rbind(splits2[[i]], ends[[i]])

#'arrange by time
splits2 = splits2 %>% map(function(x) x %>% arrange(time))

#'bind rows
splits = bind_rows(splits2)

source("days_since.r")
splits$t_since_in = days_since(splits$time)

#coordinates(splits2) = ~lon+lat

#'convert to spatial lines for tmap
#famlines = split(splits[,c("lon","lat")], f = splits$fam)

#famlines = spLines(lapply(famlines, function(x){as.matrix(x)}))

save(splits, file="splits.with.ids.rdata")
```

```{r split_for_move}
#'remove duplicates
famcoords = famcoords[!duplicated(famcoords[,c("fam","time")]),]
#'lead goose tracks
fam.move = move(famcoords$lon, famcoords$lat, time = famcoords$time,
               animal = famcoords$fam, proj = CRS("+proj=longlat +ellps=WGS84"))

#'now split again
fam.move = split(fam.move)
#'split the coordinates again too
famcoords = split(famcoords, f = famcoords$fam)

#'get speed, dist, lag, angle.
fam.move2 = lapply(fam.move, function(x){x = data.frame(speed = c(NA, speed(x)), dist = c(NA, distance(x)), angle = c(NA, angle(x)), lag = c(NA, timeLag(x)), lon = coordinates(x)[,1], lat = coordinates(x)[,2], time = timestamps(x))})

for(i in 1:13){
  fam.move2[[i]]$fam = names(fam.move2)[i]
}

#'now rbind
fam.move2 = bind_rows(fam.move2)

#'add splits
fam.move2 = merge(fam.move2,splits %>% select(time, fam, event), by = c("time", "fam"), all.x = T)

fam.move2 = merge(fam.move2, daycoords[,c("fam","time","fsize")], by = c("fam","time"))

fam.move2 =  fam.move2 %>% arrange(fam, time)

fam.move2$event = ifelse(is.na(fam.move2$event), "other", fam.move2$event)

fam.move2$event = as.factor(fam.move2$event)
```

```{r save_split_data}
save(daycoords, splits, famcoords, fam.move, file = "fsize_coords.rdata")
```