---
title: GAMs on juvenile proportion
output: beamer_presentation
---

```{r, include=FALSE}
#'load knitr
library(knitr)
library(ggplot2)
library(lme4)
library(lubridate)
library(car)
library(mgcv)
library(gamm4)
#'suppress all code output but run code
opts_chunk$set(echo = FALSE)
opts_knit$set(root.dir = "~/git/thesis/code")
```

```{r import_data, include = FALSE}
#'load geese, fams and fams expanded
geese = read.csv("data.goose.clean.csv", row.names = 1)
fams = read.csv("fams.csv", row.names = 1)
fams.expand = read.csv("fams.expand.csv")

#'convery perc to prop
geese$propjuv = round(geese$propjuv/100, 4)

#'drop zone Other
geese = geese[geese$zone != "Other",]

#'juvenile proportion is actually N_juv/N_sampled
#plot(geese$propjuv2 ~ geese$propjuv,
  #   main = "Calculated vs provided juv prop.",
  #   xlab = "Provided in data",
  #   ylab = "Calculated as N_juvs/No. of whitefronts")

#'change class of time variable to Date
geese$time = as.Date(geese$time)
fams$time = as.Date(fams$time)
fams.expand$time = as.Date(fams.expand$time)

#'add month and day
geese$month = month(geese$time)
geese$day = day(geese$time)
```

# Juvenile proportion

## Juvenile proportion ~ time

### GAM, propjuv ~ s(time)

```{r gam_time01, include=FALSE}
library(mgcv)
#'run a trial gam
gam_time01 = gam(propjuv ~ s(as.numeric(time)), 
                 family = "binomial", data = geese,
                 na.action = na.omit)

#'summary
summary(gam_time01)

gam_time01b = gam(propjuv ~ s(Breeding_year), 
                 family = "binomial", data = geese,
                 na.action = na.omit)

#'summary
summary(gam_time01b)
#'time is has a significant effect, but the model explains only 30% of the variance.
```

```{r plot_gam_time}
#'plot it
mgcv::plot.gam(gam_time01, residuals = T, shade = T,
               main = "GAM, propjuv ~ s(time)", xlab = "time", 
               ylab = "s(time)")
```


### GAMM, propjuv ~ s(time)

```{r gamm_time01, include=FALSE}
#'random effects are added: observer, flocksize, foodtype/habitat. the underlying mixed effects model is taken from the package nlme, could be updated to use lme4 via the gamm4 package.

gamm_time01 = gamm(propjuv ~ s(as.numeric(time)),
          random = list(flocksize=~1, Observer = ~1, Food_type=~ 1),
                   data = geese, family = "binomial", na.action = na.omit)

#'summary
plot(gamm_time01$lme, residuals = T)

summary(gamm_time01$gam)
summary(gamm_time01$lme)

#'the random effects explain very little of the variation and can be removed.
```

## Juvenile proportion ~ year * month

### GAM

```{r winter_month}
#'classify months based on their order in the winter
geese$winter_month =  c(c(1:8), geese$month)[match(geese$month, c(c(9:12,1:4), geese$month))]
```


```{r gam_time02}
#'attempt to separate the effects of year and month in the gam. use a tensor interaction smooth since month and year are on different scales, and since we want to remove the effects of only year and only month(not really calculated) from the interacting effect.
gam_time02a = gam(propjuv ~ ti(Breeding_year) + ti(Breeding_year, winter_month), 
                 family = "binomial", data = geese,
                 na.action = na.omit)

#'plot
plot(gam_time02a, residuals = T)

#'visualise it
vis.gam(gam_time02a, 
        theta = 10, phi = 25, 
        plot.type = "persp", 
        ticktype = "detailed", 
        type = "response", 
        zlab = "juvenile proportion",
        color = "terrain")

#'summarise
summary(gam_time02a)

#'while the model explains around 31% of the variance, breeding year is the only significant factor, with the interaction of year and month not very important.
```

## Juvenile proportion ~ long * lat

```{r rand_coords, include=FALSE}
#'each record is assigned a random longitude drawn from a normal distribution with the longitude of that record's zone as the mean and a standard deviation of 0.1. even an high latitudes, a 0.1 decimal degree variation would result in a concentration of records within 20km of the defined zonal longitude.

geese$rand.lon = rnorm(length(geese$lon), geese$lon, 0.1)
geese$rand.lat = rnorm(length(geese$lat), geese$lat, 0.1)

#'a density plot of the random longitudes
with(geese, plot(rand.lon, rand.lat, cex = 0.1, pch = 4))
library(maps)
map("world",add = T)
#'this plot looks like one would expect.
```

### Juvenile proportion ~ long + lat

```{r gam.zone01a}
#'long and lat are interacting factors, the function s() is appropriate since they have the same scale.
gam.zone01a = gam(propjuv ~ s(rand.lon) + s(rand.lat) + ti(rand.lon, rand.lat), data = geese, family = "binomial", na.action = na.omit)

#'plot it, doesn't look very helpful
plot(gam.zone01a)

#'visualise as a 3d surface
vis.gam(gam.zone01a, type = "response", theta = 10, phi = 45, 
        plot.type = "persp", 
        ticktype = "detailed",
        zlab = "juvenile proportion",
        color = "terrain")

#'summary
summary(gam.zone01a)
#'neither longitude, latitude nor the interaction show any significant effect.
```
## Juvenile proportion ~ zone * year * month

```{r gam_global01}
#'this is a global gam, considering both space and time. if this doesn't differ significantly from the temporal gam, the zone (as coordinates), will be pushed to random effects and a global GAMM run on the year and month.

gam_global01 = gam(propjuv ~ s(Breeding_year) + ti(winter_month) + s(rand.lat) + s(rand.lon) + te(Breeding_year, winter_month) + te(Breeding_year, winter_month, rand.lon, rand.lat) + s(rand.lat, rand.lon) + te(Breeding_year, rand.lon) + te(Breeding_year, rand.lat),  data = geese, family = "binomial", na.action = na.omit)

#'plot it
vis.gam(gam_global01, type = "response", view = c("Breeding_year","winter_month"),theta = 10, phi = 25, 
        plot.type = "persp", 
        ticktype = "detailed",
        zlab = "juvenile proportion",
        color = "terrain")

#'summary
summary(gam_global01)

#'compare
anova(gam_global01, gam_time02a, test = "F")

#'no significant difference between a global model and a model with only the year and the month. appears as though year is the driving factor.
```

```{r gam_global02, eval=FALSE}
#'prune all non-significant terms
gam_global02 = gam(propjuv ~ s(Breeding_year, winter_month, rand.lat, rand.lon) + s(Breeding_year, winter_month, rand.lon) + s(Breeding_year, rand.lon) + s(winter_month, rand.lon), data = geese, family = "binomial", na.action = na.omit)
```


